package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * MdPath Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "MdPath")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "MdPath")
public class MdPath implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "pathName")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pathName;

    @Column(name = "path")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String path;

    @Column(name = "pathType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer pathType;
    
    
    @ManyToOne
    @JoinColumn(name="mdClassId")
    private MdClass mdClass;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getPathName() {
        return pathName;
    }
    
    public void setPathName(String pathName) {
        this.pathName = pathName;
    }
    
    public String getPath() {
        return path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    
    public Integer getPathType() {
        return pathType;
    }
    
    public void setPathType(Integer pathType) {
        this.pathType = pathType;
    }
    
    public MdClass getMdClass() {
        return mdClass;
    }
    
    public void setMdClass(MdClass mdClass) {
        this.mdClass = mdClass;
    }


    public MdPath() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof MdPath))
            return false;
        MdPath equalCheck = (MdPath) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}