package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmCustomerContact Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmCustomerContact")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmCustomerContact")
public class TlmCustomerContact implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "allUnits")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean allUnits;

    @Column(name = "allUnitsAsExcel")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean allUnitsAsExcel;

    @Column(name = "bolAtDispatch")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean bolAtDispatch;

    @Column(name = "bolAtOrderEntry")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean bolAtOrderEntry;

    @Column(name = "breakdown")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean breakdown;

    @Column(name = "callback")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date callback;

    @Column(name = "checkIn")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean checkIn;

    @Column(name = "checkOut")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean checkOut;

    @Column(name = "contactFor")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String contactFor;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "creditCardCharges")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean creditCardCharges;

    @Column(name = "damage")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean damage;

    @Column(name = "delay")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean delay;

    @Column(name = "deliveredUnitsAsExcel")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean deliveredUnitsAsExcel;

    @Column(name = "deliveredUnitsReport")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean deliveredUnitsReport;

    @Column(name = "delivery")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean delivery;

    @Column(name = "email")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String email;

    @Column(name = "fax")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String fax;

    @Column(name = "invoices")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean invoices;

    @Column(name = "lastCall")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastCall;

    @Column(name = "name")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String name;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "phone")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String phone;

    @Column(name = "reroute")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean reroute;

    @Column(name = "returned")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean returned;

    @Column(name = "specialCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String specialCode;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "unassignedUnitsAsExcel")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean unassignedUnitsAsExcel;

    @Column(name = "unassignedUnitsReport")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean unassignedUnitsReport;

    @Column(name = "undispatch")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean undispatch;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "yardExitAsExcel")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean yardExitAsExcel;

    @Column(name = "yardExitReport")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean yardExitReport;
    
    @Column(name = "asap")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean asap;
    
    @Column(name = "dueBy")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean dueBy;
    
    @Column(name = "hot")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean hot;
    
    @Column(name = "showCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean showCode;
    
    @Column(name = "sold")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean sold;
    
    @Column(name = "willPickUp")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean willPickUp;

    @Column(name = "isLogin")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String isLogin;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="customerId")
    private TlmCustomer customer;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;
    
    @ManyToOne
    @JoinColumn(name="userLoginId")
    private UserLogin userLogin;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Boolean getAllUnits() {
        return allUnits;
    }
    
    public void setAllUnits(Boolean allUnits) {
        this.allUnits = allUnits;
    }
    
    public Boolean getAllUnitsAsExcel() {
        return allUnitsAsExcel;
    }
    
    public void setAllUnitsAsExcel(Boolean allUnitsAsExcel) {
        this.allUnitsAsExcel = allUnitsAsExcel;
    }
    
    public Boolean getBolAtDispatch() {
        return bolAtDispatch;
    }
    
    public void setBolAtDispatch(Boolean bolAtDispatch) {
        this.bolAtDispatch = bolAtDispatch;
    }
    
    public Boolean getBolAtOrderEntry() {
        return bolAtOrderEntry;
    }
    
    public void setBolAtOrderEntry(Boolean bolAtOrderEntry) {
        this.bolAtOrderEntry = bolAtOrderEntry;
    }
    
    public Boolean getBreakdown() {
        return breakdown;
    }
    
    public void setBreakdown(Boolean breakdown) {
        this.breakdown = breakdown;
    }
    
    public Date getCallback() {
        return callback;
    }
    
    public void setCallback(Date callback) {
        this.callback = callback;
    }
    
    public Boolean getCheckIn() {
        return checkIn;
    }
    
    public void setCheckIn(Boolean checkIn) {
        this.checkIn = checkIn;
    }
    
    public Boolean getCheckOut() {
        return checkOut;
    }
    
    public void setCheckOut(Boolean checkOut) {
        this.checkOut = checkOut;
    }
    
    public String getContactFor() {
        return contactFor;
    }
    
    public void setContactFor(String contactFor) {
        this.contactFor = contactFor;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Boolean getCreditCardCharges() {
        return creditCardCharges;
    }
    
    public void setCreditCardCharges(Boolean creditCardCharges) {
        this.creditCardCharges = creditCardCharges;
    }
    
    public Boolean getDamage() {
        return damage;
    }
    
    public void setDamage(Boolean damage) {
        this.damage = damage;
    }
    
    public Boolean getDelay() {
        return delay;
    }
    
    public void setDelay(Boolean delay) {
        this.delay = delay;
    }
    
    public Boolean getDeliveredUnitsAsExcel() {
        return deliveredUnitsAsExcel;
    }
    
    public void setDeliveredUnitsAsExcel(Boolean deliveredUnitsAsExcel) {
        this.deliveredUnitsAsExcel = deliveredUnitsAsExcel;
    }
    
    public Boolean getDeliveredUnitsReport() {
        return deliveredUnitsReport;
    }
    
    public void setDeliveredUnitsReport(Boolean deliveredUnitsReport) {
        this.deliveredUnitsReport = deliveredUnitsReport;
    }
    
    public Boolean getDelivery() {
        return delivery;
    }
    
    public void setDelivery(Boolean delivery) {
        this.delivery = delivery;
    }
    
    public String getEmail() {
        return email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getFax() {
        return fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    public Boolean getInvoices() {
        return invoices;
    }
    
    public void setInvoices(Boolean invoices) {
        this.invoices = invoices;
    }
    
    public Date getLastCall() {
        return lastCall;
    }
    
    public void setLastCall(Date lastCall) {
        this.lastCall = lastCall;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public String getPhone() {
        return phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIsLogin() {
        return isLogin;
    }
    
    public void setIsLogin(String isLogin) {
        this.isLogin = isLogin;
    }
    
    public Boolean getReroute() {
        return reroute;
    }
    
    public void setReroute(Boolean reroute) {
        this.reroute = reroute;
    }
    
    public Boolean getReturned() {
        return returned;
    }
    
    public void setReturned(Boolean returned) {
        this.returned = returned;
    }
    
    public String getSpecialCode() {
        return specialCode;
    }
    
    public void setSpecialCode(String specialCode) {
        this.specialCode = specialCode;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Boolean getUnassignedUnitsAsExcel() {
        return unassignedUnitsAsExcel;
    }
    
    public void setUnassignedUnitsAsExcel(Boolean unassignedUnitsAsExcel) {
        this.unassignedUnitsAsExcel = unassignedUnitsAsExcel;
    }
    
    public Boolean getUnassignedUnitsReport() {
        return unassignedUnitsReport;
    }
    
    public void setUnassignedUnitsReport(Boolean unassignedUnitsReport) {
        this.unassignedUnitsReport = unassignedUnitsReport;
    }
    
    public Boolean getUndispatch() {
        return undispatch;
    }
    
    public void setUndispatch(Boolean undispatch) {
        this.undispatch = undispatch;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public Boolean getYardExitAsExcel() {
        return yardExitAsExcel;
    }
    
    public void setYardExitAsExcel(Boolean yardExitAsExcel) {
        this.yardExitAsExcel = yardExitAsExcel;
    }
    
    public Boolean getYardExitReport() {
        return yardExitReport;
    }
    
    public void setYardExitReport(Boolean yardExitReport) {
        this.yardExitReport = yardExitReport;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmCustomer getCustomer() {
        return customer;
    }
    
    public void setCustomer(TlmCustomer customer) {
        this.customer = customer;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }
    
    public UserLogin getUserLogin() {
        return userLogin;
    }
    
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
   
    public Boolean getAsap() {
		return asap;
	}

	public void setAsap(Boolean asap) {
		this.asap = asap;
	}

	public Boolean getDueBy() {
		return dueBy;
	}

	public void setDueBy(Boolean dueBy) {
		this.dueBy = dueBy;
	}

	public Boolean getHot() {
		return hot;
	}

	public void setHot(Boolean hot) {
		this.hot = hot;
	}

	public Boolean getShowCode() {
		return showCode;
	}

	public void setShowCode(Boolean showCode) {
		this.showCode = showCode;
	}

	public Boolean getSold() {
		return sold;
	}

	public void setSold(Boolean sold) {
		this.sold = sold;
	}

	public Boolean getWillPickUp() {
		return willPickUp;
	}

	public void setWillPickUp(Boolean willPickUp) {
		this.willPickUp = willPickUp;
	}

	public TlmCustomerContact() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmCustomerContact))
            return false;
        TlmCustomerContact equalCheck = (TlmCustomerContact) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}