package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDriverDrugTest Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDriverDrugTest")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDriverDrugTest")
public class TlmDriverDrugTest implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "adulterate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean adulterate;

    @Column(name = "alcoholCanceledReason")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String alcoholCanceledReason;

    @Column(name = "alcoholTest")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean alcoholTest;

    @Column(name = "alcoholTestCanceled")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean alcoholTestCanceled;

    @Column(name = "alcoholTestPlus")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String alcoholTestPlus;

    @Column(name = "alcoholTestPositive")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean alcoholTestPositive;

    @Column(name = "caseNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String caseNumber;

    @Column(name = "clinic")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String clinic;

    @Column(name = "cocaine")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean cocaine;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "datePaid")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date datePaid;

    @Column(name = "drugCanceledReason")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String drugCanceledReason;

    @Column(name = "drugTest")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean drugTest;

    @Column(name = "drugTestCanceled")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean drugTestCanceled;

    @Column(name = "drugTestPositive")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean drugTestPositive;

    @Column(name = "invoiceAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer invoiceAmount;

    @Column(name = "invoiceDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date invoiceDate;

    @Column(name = "invoiceNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String invoiceNumber;

    @Column(name = "marijuana")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean marijuana;

    @Column(name = "meth")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean meth;

    @Column(name = "notTested")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean notTested;

    @Column(name = "notTestedReason")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notTestedReason;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "notificationDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date notificationDate;

    @Column(name = "opiates")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean opiates;

    @Column(name = "other")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean other;

    @Column(name = "otherDescription")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String otherDescription;

    @Column(name = "pCP")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean pCP;

    @Column(name = "refusedAlcoholTest")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean refusedAlcoholTest;

    @Column(name = "refusedDrugTest")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean refusedDrugTest;

    @Column(name = "resultsDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date resultsDate;

    @Column(name = "selectionDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date selectionDate;

    @Column(name = "source")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String source;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "testDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date testDate;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "notificationUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger notificationUserFK;

    @Column(name = "resultsUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger resultsUserFK;

    @Column(name = "selectionUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger selectionUserFK;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="driverId")
    private TlmDriver driver;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Boolean getAdulterate() {
        return adulterate;
    }
    
    public void setAdulterate(Boolean adulterate) {
        this.adulterate = adulterate;
    }
    
    public String getAlcoholCanceledReason() {
        return alcoholCanceledReason;
    }
    
    public void setAlcoholCanceledReason(String alcoholCanceledReason) {
        this.alcoholCanceledReason = alcoholCanceledReason;
    }
    
    public Boolean getAlcoholTest() {
        return alcoholTest;
    }
    
    public void setAlcoholTest(Boolean alcoholTest) {
        this.alcoholTest = alcoholTest;
    }
    
    public Boolean getAlcoholTestCanceled() {
        return alcoholTestCanceled;
    }
    
    public void setAlcoholTestCanceled(Boolean alcoholTestCanceled) {
        this.alcoholTestCanceled = alcoholTestCanceled;
    }
    
    public String getAlcoholTestPlus() {
        return alcoholTestPlus;
    }
    
    public void setAlcoholTestPlus(String alcoholTestPlus) {
        this.alcoholTestPlus = alcoholTestPlus;
    }
    
    public Boolean getAlcoholTestPositive() {
        return alcoholTestPositive;
    }
    
    public void setAlcoholTestPositive(Boolean alcoholTestPositive) {
        this.alcoholTestPositive = alcoholTestPositive;
    }
    
    public String getCaseNumber() {
        return caseNumber;
    }
    
    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber;
    }
    
    public String getClinic() {
        return clinic;
    }
    
    public void setClinic(String clinic) {
        this.clinic = clinic;
    }
    
    public Boolean getCocaine() {
        return cocaine;
    }
    
    public void setCocaine(Boolean cocaine) {
        this.cocaine = cocaine;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Date getDatePaid() {
        return datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    
    public String getDrugCanceledReason() {
        return drugCanceledReason;
    }
    
    public void setDrugCanceledReason(String drugCanceledReason) {
        this.drugCanceledReason = drugCanceledReason;
    }
    
    public Boolean getDrugTest() {
        return drugTest;
    }
    
    public void setDrugTest(Boolean drugTest) {
        this.drugTest = drugTest;
    }
    
    public Boolean getDrugTestCanceled() {
        return drugTestCanceled;
    }
    
    public void setDrugTestCanceled(Boolean drugTestCanceled) {
        this.drugTestCanceled = drugTestCanceled;
    }
    
    public Boolean getDrugTestPositive() {
        return drugTestPositive;
    }
    
    public void setDrugTestPositive(Boolean drugTestPositive) {
        this.drugTestPositive = drugTestPositive;
    }
    
    public Integer getInvoiceAmount() {
        return invoiceAmount;
    }
    
    public void setInvoiceAmount(Integer invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }
    
    public Date getInvoiceDate() {
        return invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    
    public String getInvoiceNumber() {
        return invoiceNumber;
    }
    
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    
    public Boolean getMarijuana() {
        return marijuana;
    }
    
    public void setMarijuana(Boolean marijuana) {
        this.marijuana = marijuana;
    }
    
    public Boolean getMeth() {
        return meth;
    }
    
    public void setMeth(Boolean meth) {
        this.meth = meth;
    }
    
    public Boolean getNotTested() {
        return notTested;
    }
    
    public void setNotTested(Boolean notTested) {
        this.notTested = notTested;
    }
    
    public String getNotTestedReason() {
        return notTestedReason;
    }
    
    public void setNotTestedReason(String notTestedReason) {
        this.notTestedReason = notTestedReason;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public Date getNotificationDate() {
        return notificationDate;
    }
    
    public void setNotificationDate(Date notificationDate) {
        this.notificationDate = notificationDate;
    }
    
    public Boolean getOpiates() {
        return opiates;
    }
    
    public void setOpiates(Boolean opiates) {
        this.opiates = opiates;
    }
    
    public Boolean getOther() {
        return other;
    }
    
    public void setOther(Boolean other) {
        this.other = other;
    }
    
    public String getOtherDescription() {
        return otherDescription;
    }
    
    public void setOtherDescription(String otherDescription) {
        this.otherDescription = otherDescription;
    }
    
    public Boolean getPCP() {
        return pCP;
    }
    
    public void setPCP(Boolean pCP) {
        this.pCP = pCP;
    }
    
    public Boolean getRefusedAlcoholTest() {
        return refusedAlcoholTest;
    }
    
    public void setRefusedAlcoholTest(Boolean refusedAlcoholTest) {
        this.refusedAlcoholTest = refusedAlcoholTest;
    }
    
    public Boolean getRefusedDrugTest() {
        return refusedDrugTest;
    }
    
    public void setRefusedDrugTest(Boolean refusedDrugTest) {
        this.refusedDrugTest = refusedDrugTest;
    }
    
    public Date getResultsDate() {
        return resultsDate;
    }
    
    public void setResultsDate(Date resultsDate) {
        this.resultsDate = resultsDate;
    }
    
    public Date getSelectionDate() {
        return selectionDate;
    }
    
    public void setSelectionDate(Date selectionDate) {
        this.selectionDate = selectionDate;
    }
    
    public String getSource() {
        return source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Date getTestDate() {
        return testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public BigInteger getNotificationUserFK() {
        return notificationUserFK;
    }
    
    public void setNotificationUserFK(BigInteger notificationUserFK) {
        this.notificationUserFK = notificationUserFK;
    }
    
    public BigInteger getResultsUserFK() {
        return resultsUserFK;
    }
    
    public void setResultsUserFK(BigInteger resultsUserFK) {
        this.resultsUserFK = resultsUserFK;
    }
    
    public BigInteger getSelectionUserFK() {
        return selectionUserFK;
    }
    
    public void setSelectionUserFK(BigInteger selectionUserFK) {
        this.selectionUserFK = selectionUserFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDriver getDriver() {
        return driver;
    }
    
    public void setDriver(TlmDriver driver) {
        this.driver = driver;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmDriverDrugTest() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDriverDrugTest))
            return false;
        TlmDriverDrugTest equalCheck = (TlmDriverDrugTest) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}