package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDelayedUnitUpdate Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDelayedUnitUpdate")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDelayedUnitUpdate")
public class TlmDelayedUnitUpdate implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "customerEmailed")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean customerEmailed;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "updateAction")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String updateAction;

    @Column(name = "updateNote")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String updateNote;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "updatingUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger updatingUserFK;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="delayedUnitId")
    private TlmDelayedUnit delayedUnit;
    
    @ManyToOne
    @JoinColumn(name="unitId")
    private TlmUnit unit;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Boolean getCustomerEmailed() {
        return customerEmailed;
    }
    
    public void setCustomerEmailed(Boolean customerEmailed) {
        this.customerEmailed = customerEmailed;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public String getUpdateAction() {
        return updateAction;
    }
    
    public void setUpdateAction(String updateAction) {
        this.updateAction = updateAction;
    }
    
    public String getUpdateNote() {
        return updateNote;
    }
    
    public void setUpdateNote(String updateNote) {
        this.updateNote = updateNote;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public BigInteger getUpdatingUserFK() {
        return updatingUserFK;
    }
    
    public void setUpdatingUserFK(BigInteger updatingUserFK) {
        this.updatingUserFK = updatingUserFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDelayedUnit getDelayedUnit() {
        return delayedUnit;
    }
    
    public void setDelayedUnit(TlmDelayedUnit delayedUnit) {
        this.delayedUnit = delayedUnit;
    }
    
    public TlmUnit getUnit() {
        return unit;
    }
    
    public void setUnit(TlmUnit unit) {
        this.unit = unit;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmDelayedUnitUpdate() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDelayedUnitUpdate))
            return false;
        TlmDelayedUnitUpdate equalCheck = (TlmDelayedUnitUpdate) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}