package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDelayedUnitDamage Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDelayedUnitDamage")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDelayedUnitDamage")
public class TlmDelayedUnitDamage implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "alcoholTest")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean alcoholTest;

    @Column(name = "atFault")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean atFault;

    @Column(name = "chargeable")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean chargeable;

    @Column(name = "checkPayTo")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String checkPayTo;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "damageAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer damageAmount;

    @Column(name = "damageDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date damageDate;

    @Column(name = "dotReportable")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean dotReportable;

    @Column(name = "driverAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer driverAmount;

    @Column(name = "drugTest")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean drugTest;

    @Column(name = "insuranceClaimNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceClaimNumber;

    @Column(name = "insuranceContact")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceContact;

    @Column(name = "insuranceLiabilityNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceLiabilityNumber;

    @Column(name = "insuranceName")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceName;

    @Column(name = "insurancePhone")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insurancePhone;

    @Column(name = "keepStar")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean keepStar;

    @Column(name = "lostSafetyMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer lostSafetyMiles;

    @Column(name = "name")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String name;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "ourClaimNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String ourClaimNumber;
 
    @Column(name = "phone")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String phone;

    @Column(name = "responcibleParty")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean responcibleParty;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "statusComment")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String statusComment;

    @Column(name = "theirClaimNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String theirClaimNumber;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "insuranceCity")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceCity;

    @Column(name = "insuranceCountryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceCountryCode;

    @Column(name = "insurancePostalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insurancePostalCode;

    @Column(name = "insuranceStateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceStateCode;

    @Column(name = "insuranceAddress1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceAddress1;

    @Column(name = "insuranceAddress2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String insuranceAddress2;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="driverId")
    private TlmDriver driver;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;
    
    @ManyToOne
    @JoinColumn(name="delayedUnitId")
    private TlmDelayedUnit delayedUnit;


    public TlmDelayedUnit getDelayedUnit() {
		return delayedUnit;
	}

	public void setDelayedUnit(TlmDelayedUnit delayedUnit) {
		this.delayedUnit = delayedUnit;
	}

	public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Boolean getAlcoholTest() {
        return alcoholTest;
    }
    
    public void setAlcoholTest(Boolean alcoholTest) {
        this.alcoholTest = alcoholTest;
    }
    
    public Boolean getAtFault() {
        return atFault;
    }
    
    public void setAtFault(Boolean atFault) {
        this.atFault = atFault;
    }
    
    public Boolean getChargeable() {
        return chargeable;
    }
    
    public void setChargeable(Boolean chargeable) {
        this.chargeable = chargeable;
    }
    
    public String getCheckPayTo() {
        return checkPayTo;
    }
    
    public void setCheckPayTo(String checkPayTo) {
        this.checkPayTo = checkPayTo;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Integer getDamageAmount() {
        return damageAmount;
    }
    
    public void setDamageAmount(Integer damageAmount) {
        this.damageAmount = damageAmount;
    }
    
    public Date getDamageDate() {
        return damageDate;
    }
    
    public void setDamageDate(Date damageDate) {
        this.damageDate = damageDate;
    }
    
    public Boolean getDotReportable() {
        return dotReportable;
    }
    
    public void setDotReportable(Boolean dotReportable) {
        this.dotReportable = dotReportable;
    }
    
    public Integer getDriverAmount() {
        return driverAmount;
    }
    
    public void setDriverAmount(Integer driverAmount) {
        this.driverAmount = driverAmount;
    }
    
    public Boolean getDrugTest() {
        return drugTest;
    }
    
    public void setDrugTest(Boolean drugTest) {
        this.drugTest = drugTest;
    }
    
    public String getInsuranceClaimNumber() {
        return insuranceClaimNumber;
    }
    
    public void setInsuranceClaimNumber(String insuranceClaimNumber) {
        this.insuranceClaimNumber = insuranceClaimNumber;
    }
    
    public String getInsuranceContact() {
        return insuranceContact;
    }
    
    public void setInsuranceContact(String insuranceContact) {
        this.insuranceContact = insuranceContact;
    }
    
    public String getInsuranceLiabilityNumber() {
        return insuranceLiabilityNumber;
    }
    
    public void setInsuranceLiabilityNumber(String insuranceLiabilityNumber) {
        this.insuranceLiabilityNumber = insuranceLiabilityNumber;
    }
    
    public String getInsuranceName() {
        return insuranceName;
    }
    
    public void setInsuranceName(String insuranceName) {
        this.insuranceName = insuranceName;
    }
    
    public String getInsurancePhone() {
        return insurancePhone;
    }
    
    public void setInsurancePhone(String insurancePhone) {
        this.insurancePhone = insurancePhone;
    }
    
    public Boolean getKeepStar() {
        return keepStar;
    }
    
    public void setKeepStar(Boolean keepStar) {
        this.keepStar = keepStar;
    }
    
    public Integer getLostSafetyMiles() {
        return lostSafetyMiles;
    }
    
    public void setLostSafetyMiles(Integer lostSafetyMiles) {
        this.lostSafetyMiles = lostSafetyMiles;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public String getOurClaimNumber() {
        return ourClaimNumber;
    }
    
    public void setOurClaimNumber(String ourClaimNumber) {
        this.ourClaimNumber = ourClaimNumber;
    }

    public String getPhone() {
        return phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    public Boolean getResponcibleParty() {
        return responcibleParty;
    }
    
    public void setResponcibleParty(Boolean responcibleParty) {
        this.responcibleParty = responcibleParty;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public String getStatusComment() {
        return statusComment;
    }
    
    public void setStatusComment(String statusComment) {
        this.statusComment = statusComment;
    }
    
    public String getTheirClaimNumber() {
        return theirClaimNumber;
    }
    
    public void setTheirClaimNumber(String theirClaimNumber) {
        this.theirClaimNumber = theirClaimNumber;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public String getInsuranceCity() {
        return insuranceCity;
    }
    
    public void setInsuranceCity(String insuranceCity) {
        this.insuranceCity = insuranceCity;
    }
    
    public String getInsuranceCountryCode() {
        return insuranceCountryCode;
    }
    
    public void setInsuranceCountryCode(String insuranceCountryCode) {
        this.insuranceCountryCode = insuranceCountryCode;
    }
    
    public String getInsurancePostalCode() {
        return insurancePostalCode;
    }
    
    public void setInsurancePostalCode(String insurancePostalCode) {
        this.insurancePostalCode = insurancePostalCode;
    }
    
    public String getInsuranceStateCode() {
        return insuranceStateCode;
    }
    
    public void setInsuranceStateCode(String insuranceStateCode) {
        this.insuranceStateCode = insuranceStateCode;
    }
    
    public String getInsuranceAddress1() {
        return insuranceAddress1;
    }
    
    public void setInsuranceAddress1(String insuranceAddress1) {
        this.insuranceAddress1 = insuranceAddress1;
    }
    
    public String getInsuranceAddress2() {
        return insuranceAddress2;
    }
    
    public void setInsuranceAddress2(String insuranceAddress2) {
        this.insuranceAddress2 = insuranceAddress2;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDriver getDriver() {
        return driver;
    }
    
    public void setDriver(TlmDriver driver) {
        this.driver = driver;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmDelayedUnitDamage() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDelayedUnitDamage))
            return false;
        TlmDelayedUnitDamage equalCheck = (TlmDelayedUnitDamage) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}