package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDriverSchedule Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDriverSchedule")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDriverSchedule")
public class TlmDriverSchedule implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "scheduleMonth")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date scheduleMonth;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "dAY_01")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_01;

    @Column(name = "dAY_02")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_02;

    @Column(name = "dAY_03")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_03;

    @Column(name = "dAY_04")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_04;

    @Column(name = "dAY_05")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_05;

    @Column(name = "dAY_06")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_06;

    @Column(name = "dAY_07")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_07;

    @Column(name = "dAY_08")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_08;

    @Column(name = "dAY_09")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_09;

    @Column(name = "dAY_10")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_10;

    @Column(name = "dAY_11")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_11;

    @Column(name = "dAY_12")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_12;

    @Column(name = "dAY_13")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_13;

    @Column(name = "dAY_14")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_14;

    @Column(name = "dAY_15")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_15;

    @Column(name = "dAY_16")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_16;

    @Column(name = "dAY_17")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_17;

    @Column(name = "dAY_18")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_18;

    @Column(name = "dAY_19")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_19;

    @Column(name = "dAY_20")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_20;

    @Column(name = "dAY_21")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_21;

    @Column(name = "dAY_22")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_22;

    @Column(name = "dAY_23")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_23;

    @Column(name = "dAY_24")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_24;

    @Column(name = "dAY_25")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_25;

    @Column(name = "dAY_26")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_26;

    @Column(name = "dAY_27")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_27;

    @Column(name = "dAY_28")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_28;

    @Column(name = "dAY_29")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_29;

    @Column(name = "dAY_30")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_30;

    @Column(name = "dAY_31")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dAY_31;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="driverId")
    private TlmDriver driver;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Date getScheduleMonth() {
        return scheduleMonth;
    }
    
    public void setScheduleMonth(Date scheduleMonth) {
        this.scheduleMonth = scheduleMonth;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public String getDAY_01() {
        return dAY_01;
    }
    
    public void setDAY_01(String dAY_01) {
        this.dAY_01 = dAY_01;
    }
    
    public String getDAY_02() {
        return dAY_02;
    }
    
    public void setDAY_02(String dAY_02) {
        this.dAY_02 = dAY_02;
    }
    
    public String getDAY_03() {
        return dAY_03;
    }
    
    public void setDAY_03(String dAY_03) {
        this.dAY_03 = dAY_03;
    }
    
    public String getDAY_04() {
        return dAY_04;
    }
    
    public void setDAY_04(String dAY_04) {
        this.dAY_04 = dAY_04;
    }
    
    public String getDAY_05() {
        return dAY_05;
    }
    
    public void setDAY_05(String dAY_05) {
        this.dAY_05 = dAY_05;
    }
    
    public String getDAY_06() {
        return dAY_06;
    }
    
    public void setDAY_06(String dAY_06) {
        this.dAY_06 = dAY_06;
    }
    
    public String getDAY_07() {
        return dAY_07;
    }
    
    public void setDAY_07(String dAY_07) {
        this.dAY_07 = dAY_07;
    }
    
    public String getDAY_08() {
        return dAY_08;
    }
    
    public void setDAY_08(String dAY_08) {
        this.dAY_08 = dAY_08;
    }
    
    public String getDAY_09() {
        return dAY_09;
    }
    
    public void setDAY_09(String dAY_09) {
        this.dAY_09 = dAY_09;
    }
    
    public String getDAY_10() {
        return dAY_10;
    }
    
    public void setDAY_10(String dAY_10) {
        this.dAY_10 = dAY_10;
    }
    
    public String getDAY_11() {
        return dAY_11;
    }
    
    public void setDAY_11(String dAY_11) {
        this.dAY_11 = dAY_11;
    }
    
    public String getDAY_12() {
        return dAY_12;
    }
    
    public void setDAY_12(String dAY_12) {
        this.dAY_12 = dAY_12;
    }
    
    public String getDAY_13() {
        return dAY_13;
    }
    
    public void setDAY_13(String dAY_13) {
        this.dAY_13 = dAY_13;
    }
    
    public String getDAY_14() {
        return dAY_14;
    }
    
    public void setDAY_14(String dAY_14) {
        this.dAY_14 = dAY_14;
    }
    
    public String getDAY_15() {
        return dAY_15;
    }
    
    public void setDAY_15(String dAY_15) {
        this.dAY_15 = dAY_15;
    }
    
    public String getDAY_16() {
        return dAY_16;
    }
    
    public void setDAY_16(String dAY_16) {
        this.dAY_16 = dAY_16;
    }
    
    public String getDAY_17() {
        return dAY_17;
    }
    
    public void setDAY_17(String dAY_17) {
        this.dAY_17 = dAY_17;
    }
    
    public String getDAY_18() {
        return dAY_18;
    }
    
    public void setDAY_18(String dAY_18) {
        this.dAY_18 = dAY_18;
    }
    
    public String getDAY_19() {
        return dAY_19;
    }
    
    public void setDAY_19(String dAY_19) {
        this.dAY_19 = dAY_19;
    }
    
    public String getDAY_20() {
        return dAY_20;
    }
    
    public void setDAY_20(String dAY_20) {
        this.dAY_20 = dAY_20;
    }
    
    public String getDAY_21() {
        return dAY_21;
    }
    
    public void setDAY_21(String dAY_21) {
        this.dAY_21 = dAY_21;
    }
    
    public String getDAY_22() {
        return dAY_22;
    }
    
    public void setDAY_22(String dAY_22) {
        this.dAY_22 = dAY_22;
    }
    
    public String getDAY_23() {
        return dAY_23;
    }
    
    public void setDAY_23(String dAY_23) {
        this.dAY_23 = dAY_23;
    }
    
    public String getDAY_24() {
        return dAY_24;
    }
    
    public void setDAY_24(String dAY_24) {
        this.dAY_24 = dAY_24;
    }
    
    public String getDAY_25() {
        return dAY_25;
    }
    
    public void setDAY_25(String dAY_25) {
        this.dAY_25 = dAY_25;
    }
    
    public String getDAY_26() {
        return dAY_26;
    }
    
    public void setDAY_26(String dAY_26) {
        this.dAY_26 = dAY_26;
    }
    
    public String getDAY_27() {
        return dAY_27;
    }
    
    public void setDAY_27(String dAY_27) {
        this.dAY_27 = dAY_27;
    }
    
    public String getDAY_28() {
        return dAY_28;
    }
    
    public void setDAY_28(String dAY_28) {
        this.dAY_28 = dAY_28;
    }
    
    public String getDAY_29() {
        return dAY_29;
    }
    
    public void setDAY_29(String dAY_29) {
        this.dAY_29 = dAY_29;
    }
    
    public String getDAY_30() {
        return dAY_30;
    }
    
    public void setDAY_30(String dAY_30) {
        this.dAY_30 = dAY_30;
    }
    
    public String getDAY_31() {
        return dAY_31;
    }
    
    public void setDAY_31(String dAY_31) {
        this.dAY_31 = dAY_31;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDriver getDriver() {
        return driver;
    }
    
    public void setDriver(TlmDriver driver) {
        this.driver = driver;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmDriverSchedule() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDriverSchedule))
            return false;
        TlmDriverSchedule equalCheck = (TlmDriverSchedule) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}