package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDriver Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDriver")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDriver")
public class TlmDriver implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "accumulatedBond")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer accumulatedBond;

    @Column(name = "activeAlerts")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String activeAlerts;

    @Column(name = "adsLooks")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer adsLooks;

    @Column(name = "adsReloads")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean adsReloads;

    @Column(name = "alertSeverity")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String alertSeverity;

    @Column(name = "annualReview")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date annualReview;

    @Column(name = "birthday")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date birthday;

    @Column(name = "bobtailDriver")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean bobtailDriver;

    @Column(name = "bondDraws")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer bondDraws;

    @Column(name = "bondRate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer bondRate;

    @Column(name = "breakdown")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean breakdown;

    @Column(name = "busQualified")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean busQualified;

    @Column(name = "checkIn")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean checkIn;

    @Column(name = "checkInDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date checkInDate;

    @Column(name = "checkInDispatchDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date checkInDispatchDate;

    @Column(name = "checkOut")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean checkOut;

    @Column(name = "coDriver")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean coDriver;

    @Column(name = "comdataCardNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String comdataCardNumber;

    @Column(name = "comdataDirectDeposit")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean comdataDirectDeposit;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "damage")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean damage;

    @Column(name = "dba")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dba;

    @Column(name = "delay")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean delay;

    @Column(name = "delivery")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean delivery;

    @Column(name = "dhp")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dhp;

    @Column(name = "dispatchNotes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dispatchNotes;

    @Column(name = "dotPhysicalExpirationDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date dotPhysicalExpirationDate;

    @Column(name = "driverNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String driverNumber;

    @Column(name = "driversLicenseExpiration")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date driversLicenseExpiration;

    @Column(name = "driversLicenseNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String driversLicenseNumber;

    @Column(name = "driversLicenseState")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String driversLicenseState;

    @Column(name = "driversLicenseType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String driversLicenseType;

    @Column(name = "drugKit")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean drugKit;

    @Column(name = "email")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String email;

    @Column(name = "fax")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String fax;

    @Column(name = "faxPaperwork")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean faxPaperwork;

    @Column(name = "hireDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date hireDate;

    @Column(name = "hitchTowbar")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean hitchTowbar;

    @Column(name = "hobby")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String hobby;

    @Column(name = "homePhone")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String homePhone;

    @Column(name = "iftaPermitExpirationDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date iftaPermitExpirationDate;

    @Column(name = "iftaPermitNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String iftaPermitNumber;

    @Column(name = "irpPlateNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String irpPlateNumber;

    @Column(name = "lastAdsLook")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastAdsLook;

    @Column(name = "lastAlertNotice")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastAlertNotice;

    @Column(name = "lastBondDrawDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastBondDrawDate;

    @Column(name = "lastDeliveryDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastDeliveryDate;

    @Column(name = "lastDispatchDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastDispatchDate;

    @Column(name = "lastExpirationCheck")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastExpirationCheck;

    @Column(name = "lastSafety")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastSafety;

    @Column(name = "minimum4Star")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean minimum4Star;

    @Column(name = "missedCheckinCalls")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer missedCheckinCalls;

    @Column(name = "motorized")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean motorized;

    @Column(name = "motorizedClass")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String motorizedClass;

    @Column(name = "mPW")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer mPW;

    @Column(name = "multipleDispatches")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean multipleDispatches;

    @Column(name = "name")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String name;

    @Column(name = "nextLRLMonth")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String nextLRLMonth;

    @Column(name = "nextSafety")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date nextSafety;

    @Column(name = "nickName")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String nickName;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "numberOfChildren")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer numberOfChildren;

    @Column(name = "numberOfGrandKids")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer numberOfGrandKids;

    @Column(name = "otherInterests")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String otherInterests;

    @Column(name = "passport")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean passport;

    @Column(name = "payPickupFee")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean payPickupFee;

    @Column(name = "personalEmail")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String personalEmail;

    @Column(name = "personelNotes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String personelNotes;

    @Column(name = "phone")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String phone;

    @Column(name = "postToComdata")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean postToComdata;

    @Column(name = "prepaidBond")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean prepaidBond;

    @Column(name = "rapidLogDriverID")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String rapidLogDriverID;

    @Column(name = "region")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String region;

    @Column(name = "rehireDriver")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean rehireDriver;

    @Column(name = "rehiredDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date rehiredDate;

    @Column(name = "reroute")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean reroute;

    @Column(name = "returned")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean returned;

    @Column(name = "safetyAwardLevel")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String safetyAwardLevel;

    @Column(name = "safetyCertificateNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String safetyCertificateNumber;

    @Column(name = "safetyMilesLastMonth")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer safetyMilesLastMonth;

    @Column(name = "safetyMilesNextMonth")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer safetyMilesNextMonth;

    @Column(name = "safetyMilesThisMonth")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer safetyMilesThisMonth;

    @Column(name = "spouseName")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String spouseName;

    @Column(name = "starRank")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String starRank;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "tankerQualified")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean tankerQualified;

    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String taxID;

    @Column(name = "totalBond")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer totalBond;

    @Column(name = "totalBondDraws")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer totalBondDraws;

    @Column(name = "totalMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer totalMiles;

    @Column(name = "safetyMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer safetyMiles;

    @Column(name = "towCarWeight")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer towCarWeight;

    @Column(name = "towable")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean towable;

    @Column(name = "towableClass")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String towableClass;

    @Column(name = "towcar")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean towcar;

    @Column(name = "tractorQualified")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean tractorQualified;

    @Column(name = "transportation")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String transportation;

    @Column(name = "tripCount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer tripCount;

    @Column(name = "truckingCompany")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean truckingCompany;

    @Column(name = "twic")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean twic;

    @Column(name = "undispatch")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean undispatch;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "weddingAnniversery")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date weddingAnniversery;

    @Column(name = "yesterdayCheckInDispatchDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date yesterdayCheckInDispatchDate;

    @Column(name = "ytd1099Amount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer ytd1099Amount;

    @Column(name = "city")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String city;

    @Column(name = "countryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String countryCode;

    @Column(name = "postalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String postalCode;

    @Column(name = "stateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String stateCode;

    @Column(name = "address1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String address1;

    @Column(name = "address2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String address2;

    @Column(name = "pictureContentType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pictureContentType;

    @Column(name = "pictureFile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pictureFile;

    @Column(name = "checkInDispatchFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger checkInDispatchFK;

    @Column(name = "checkInUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger checkInUserFK;

    @Column(name = "dispatcherUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dispatcherUserFK;

    @Column(name = "driverFiveStarFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger driverFiveStarFK;

    @Column(name = "lastDispatchedUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger lastDispatchedUserFK;

    @Column(name = "otherDriverFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger otherDriverFK;

    @Column(name = "primaryDriverFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger primaryDriverFK;

    @Column(name = "recruitingDriverFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger recruitingDriverFK;

    @Column(name = "yesterdayCheckInDispatchFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger yesterdayCheckInDispatchFK;


    @Column(name = "isLogin")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String isLogin;

    @Column(name = "DriverAvailability")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String driverAvailability;

    
   //Created for Driver Schedule 
    
    @ManyToOne
    @JoinColumn(name="driverSchedule")
    private TlmDriverScheduleUpdate tlmDriverScheduleUpdate;
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;
    
    @ManyToOne
    @JoinColumn(name="userLoginId")
    private UserLogin userLogin;

    
    public void setTlmDriverScheduleUpdate(TlmDriverScheduleUpdate tlmDriverScheduleUpdate) {
        this.tlmDriverScheduleUpdate = tlmDriverScheduleUpdate;
    }

    public TlmDriverScheduleUpdate getTlmDriverScheduleUpdate() {
        return this.tlmDriverScheduleUpdate;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }


     public void setDriverAvailability(String driverAvailability) {
        this.driverAvailability = driverAvailability;
    }

    public String getDriverAvailability() {
        return this.driverAvailability;
    }

        
    public Integer getAccumulatedBond() {
        return accumulatedBond;
    }
    
    public void setAccumulatedBond(Integer accumulatedBond) {
        this.accumulatedBond = accumulatedBond;
    }
    
    public String getActiveAlerts() {
        return activeAlerts;
    }
    
    public void setActiveAlerts(String activeAlerts) {
        this.activeAlerts = activeAlerts;
    }
    
    public Integer getAdsLooks() {
        return adsLooks;
    }
    
    public void setAdsLooks(Integer adsLooks) {
        this.adsLooks = adsLooks;
    }
    
    public Boolean getAdsReloads() {
        return adsReloads;
    }
    
    public void setAdsReloads(Boolean adsReloads) {
        this.adsReloads = adsReloads;
    }
    
    public String getAlertSeverity() {
        return alertSeverity;
    }
    
    public void setAlertSeverity(String alertSeverity) {
        this.alertSeverity = alertSeverity;
    }
    
    public Date getAnnualReview() {
        return annualReview;
    }
    
    public void setAnnualReview(Date annualReview) {
        this.annualReview = annualReview;
    }
    
    public Date getBirthday() {
        return birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    
    public Boolean getBobtailDriver() {
        return bobtailDriver;
    }
    
    public void setBobtailDriver(Boolean bobtailDriver) {
        this.bobtailDriver = bobtailDriver;
    }
    
    public Integer getBondDraws() {
        return bondDraws;
    }
    
    public void setBondDraws(Integer bondDraws) {
        this.bondDraws = bondDraws;
    }
    
    public Integer getBondRate() {
        return bondRate;
    }
    
    public void setBondRate(Integer bondRate) {
        this.bondRate = bondRate;
    }
    
    public Boolean getBreakdown() {
        return breakdown;
    }
    
    public void setBreakdown(Boolean breakdown) {
        this.breakdown = breakdown;
    }
    
    public Boolean getBusQualified() {
        return busQualified;
    }
    
    public void setBusQualified(Boolean busQualified) {
        this.busQualified = busQualified;
    }
    
    public Boolean getCheckIn() {
        return checkIn;
    }
    
    public void setCheckIn(Boolean checkIn) {
        this.checkIn = checkIn;
    }
    
    public Date getCheckInDate() {
        return checkInDate;
    }
    
    public void setCheckInDate(Date checkInDate) {
        this.checkInDate = checkInDate;
    }
    
    public Date getCheckInDispatchDate() {
        return checkInDispatchDate;
    }
    
    public void setCheckInDispatchDate(Date checkInDispatchDate) {
        this.checkInDispatchDate = checkInDispatchDate;
    }
    
    public Boolean getCheckOut() {
        return checkOut;
    }
    
    public void setCheckOut(Boolean checkOut) {
        this.checkOut = checkOut;
    }
    
    public Boolean getCoDriver() {
        return coDriver;
    }
    
    public void setCoDriver(Boolean coDriver) {
        this.coDriver = coDriver;
    }
    
    public String getComdataCardNumber() {
        return comdataCardNumber;
    }
    
    public void setComdataCardNumber(String comdataCardNumber) {
        this.comdataCardNumber = comdataCardNumber;
    }
    
    public Boolean getComdataDirectDeposit() {
        return comdataDirectDeposit;
    }
    
    public void setComdataDirectDeposit(Boolean comdataDirectDeposit) {
        this.comdataDirectDeposit = comdataDirectDeposit;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Boolean getDamage() {
        return damage;
    }
    
    public void setDamage(Boolean damage) {
        this.damage = damage;
    }
    
    public String getDba() {
        return dba;
    }
    
    public void setDba(String dba) {
        this.dba = dba;
    }
    
    public Boolean getDelay() {
        return delay;
    }
    
    public void setDelay(Boolean delay) {
        this.delay = delay;
    }
    
    public Boolean getDelivery() {
        return delivery;
    }
    
    public void setDelivery(Boolean delivery) {
        this.delivery = delivery;
    }

    public String getIsLogin() {
        return isLogin;
    }
    
    public void setIsLogin(String isLogin) {
        this.isLogin = isLogin;
    }
    
    public String getDhp() {
        return dhp;
    }
    
    public void setDhp(String dhp) {
        this.dhp = dhp;
    }
    
    public String getDispatchNotes() {
        return dispatchNotes;
    }
    
    public void setDispatchNotes(String dispatchNotes) {
        this.dispatchNotes = dispatchNotes;
    }
    
    public Date getDotPhysicalExpirationDate() {
        return dotPhysicalExpirationDate;
    }
    
    public void setDotPhysicalExpirationDate(Date dotPhysicalExpirationDate) {
        this.dotPhysicalExpirationDate = dotPhysicalExpirationDate;
    }
    
    public String getDriverNumber() {
        return driverNumber;
    }
    
    public void setDriverNumber(String driverNumber) {
        this.driverNumber = driverNumber;
    }
    
    public Date getDriversLicenseExpiration() {
        return driversLicenseExpiration;
    }
    
    public void setDriversLicenseExpiration(Date driversLicenseExpiration) {
        this.driversLicenseExpiration = driversLicenseExpiration;
    }
    
    public String getDriversLicenseNumber() {
        return driversLicenseNumber;
    }
    
    public void setDriversLicenseNumber(String driversLicenseNumber) {
        this.driversLicenseNumber = driversLicenseNumber;
    }
    
    public String getDriversLicenseState() {
        return driversLicenseState;
    }
    
    public void setDriversLicenseState(String driversLicenseState) {
        this.driversLicenseState = driversLicenseState;
    }
    
    public String getDriversLicenseType() {
        return driversLicenseType;
    }
    
    public void setDriversLicenseType(String driversLicenseType) {
        this.driversLicenseType = driversLicenseType;
    }
    
    public Boolean getDrugKit() {
        return drugKit;
    }
    
    public void setDrugKit(Boolean drugKit) {
        this.drugKit = drugKit;
    }
    
    public String getEmail() {
        return email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getFax() {
        return fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    public Boolean getFaxPaperwork() {
        return faxPaperwork;
    }
    
    public void setFaxPaperwork(Boolean faxPaperwork) {
        this.faxPaperwork = faxPaperwork;
    }
    
    public Date getHireDate() {
        return hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    
    public Boolean getHitchTowbar() {
        return hitchTowbar;
    }
    
    public void setHitchTowbar(Boolean hitchTowbar) {
        this.hitchTowbar = hitchTowbar;
    }
    
    public String getHobby() {
        return hobby;
    }
    
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }
    
    public String getHomePhone() {
        return homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    
    public Date getIftaPermitExpirationDate() {
        return iftaPermitExpirationDate;
    }
    
    public void setIftaPermitExpirationDate(Date iftaPermitExpirationDate) {
        this.iftaPermitExpirationDate = iftaPermitExpirationDate;
    }
    
    public String getIftaPermitNumber() {
        return iftaPermitNumber;
    }
    
    public void setIftaPermitNumber(String iftaPermitNumber) {
        this.iftaPermitNumber = iftaPermitNumber;
    }
    
    public String getIrpPlateNumber() {
        return irpPlateNumber;
    }
    
    public void setIrpPlateNumber(String irpPlateNumber) {
        this.irpPlateNumber = irpPlateNumber;
    }
    
    public Date getLastAdsLook() {
        return lastAdsLook;
    }
    
    public void setLastAdsLook(Date lastAdsLook) {
        this.lastAdsLook = lastAdsLook;
    }
    
    public Date getLastAlertNotice() {
        return lastAlertNotice;
    }
    
    public void setLastAlertNotice(Date lastAlertNotice) {
        this.lastAlertNotice = lastAlertNotice;
    }
    
    public Date getLastBondDrawDate() {
        return lastBondDrawDate;
    }
    
    public void setLastBondDrawDate(Date lastBondDrawDate) {
        this.lastBondDrawDate = lastBondDrawDate;
    }
    
    public Date getLastDeliveryDate() {
        return lastDeliveryDate;
    }
    
    public void setLastDeliveryDate(Date lastDeliveryDate) {
        this.lastDeliveryDate = lastDeliveryDate;
    }
    
    public Date getLastDispatchDate() {
        return lastDispatchDate;
    }
    
    public void setLastDispatchDate(Date lastDispatchDate) {
        this.lastDispatchDate = lastDispatchDate;
    }
    
    public Date getLastExpirationCheck() {
        return lastExpirationCheck;
    }
    
    public void setLastExpirationCheck(Date lastExpirationCheck) {
        this.lastExpirationCheck = lastExpirationCheck;
    }
    
    public Date getLastSafety() {
        return lastSafety;
    }
    
    public void setLastSafety(Date lastSafety) {
        this.lastSafety = lastSafety;
    }
    
    public Boolean getMinimum4Star() {
        return minimum4Star;
    }
    
    public void setMinimum4Star(Boolean minimum4Star) {
        this.minimum4Star = minimum4Star;
    }
    
    public Integer getMissedCheckinCalls() {
        return missedCheckinCalls;
    }
    
    public void setMissedCheckinCalls(Integer missedCheckinCalls) {
        this.missedCheckinCalls = missedCheckinCalls;
    }
    
    public Boolean getMotorized() {
        return motorized;
    }
    
    public void setMotorized(Boolean motorized) {
        this.motorized = motorized;
    }
    
    public String getMotorizedClass() {
        return motorizedClass;
    }
    
    public void setMotorizedClass(String motorizedClass) {
        this.motorizedClass = motorizedClass;
    }
    
    public Integer getMPW() {
        return mPW;
    }
    
    public void setMPW(Integer mPW) {
        this.mPW = mPW;
    }
    
    public Boolean getMultipleDispatches() {
        return multipleDispatches;
    }
    
    public void setMultipleDispatches(Boolean multipleDispatches) {
        this.multipleDispatches = multipleDispatches;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getNextLRLMonth() {
        return nextLRLMonth;
    }
    
    public void setNextLRLMonth(String nextLRLMonth) {
        this.nextLRLMonth = nextLRLMonth;
    }
    
    public Date getNextSafety() {
        return nextSafety;
    }
    
    public void setNextSafety(Date nextSafety) {
        this.nextSafety = nextSafety;
    }
    
    public String getNickName() {
        return nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public Integer getNumberOfChildren() {
        return numberOfChildren;
    }
    
    public void setNumberOfChildren(Integer numberOfChildren) {
        this.numberOfChildren = numberOfChildren;
    }
    
    public Integer getNumberOfGrandKids() {
        return numberOfGrandKids;
    }
    
    public void setNumberOfGrandKids(Integer numberOfGrandKids) {
        this.numberOfGrandKids = numberOfGrandKids;
    }
    
    public String getOtherInterests() {
        return otherInterests;
    }
    
    public void setOtherInterests(String otherInterests) {
        this.otherInterests = otherInterests;
    }
    
    public Boolean getPassport() {
        return passport;
    }
    
    public void setPassport(Boolean passport) {
        this.passport = passport;
    }
    
    public Boolean getPayPickupFee() {
        return payPickupFee;
    }
    
    public void setPayPickupFee(Boolean payPickupFee) {
        this.payPickupFee = payPickupFee;
    }
    
    public String getPersonalEmail() {
        return personalEmail;
    }
    
    public void setPersonalEmail(String personalEmail) {
        this.personalEmail = personalEmail;
    }
    
    public String getPersonelNotes() {
        return personelNotes;
    }
    
    public void setPersonelNotes(String personelNotes) {
        this.personelNotes = personelNotes;
    }
    
    public String getPhone() {
        return phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    public Boolean getPostToComdata() {
        return postToComdata;
    }
    
    public void setPostToComdata(Boolean postToComdata) {
        this.postToComdata = postToComdata;
    }
    
    public Boolean getPrepaidBond() {
        return prepaidBond;
    }
    
    public void setPrepaidBond(Boolean prepaidBond) {
        this.prepaidBond = prepaidBond;
    }
    
    public String getRapidLogDriverID() {
        return rapidLogDriverID;
    }
    
    public void setRapidLogDriverID(String rapidLogDriverID) {
        this.rapidLogDriverID = rapidLogDriverID;
    }
    
    public String getRegion() {
        return region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    
    public Boolean getRehireDriver() {
        return rehireDriver;
    }
    
    public void setRehireDriver(Boolean rehireDriver) {
        this.rehireDriver = rehireDriver;
    }
    
    public Date getRehiredDate() {
        return rehiredDate;
    }
    
    public void setRehiredDate(Date rehiredDate) {
        this.rehiredDate = rehiredDate;
    }
    
    public Boolean getReroute() {
        return reroute;
    }
    
    public void setReroute(Boolean reroute) {
        this.reroute = reroute;
    }
    
    public Boolean getReturned() {
        return returned;
    }
    
    public void setReturned(Boolean returned) {
        this.returned = returned;
    }
    
    public String getSafetyAwardLevel() {
        return safetyAwardLevel;
    }
    
    public void setSafetyAwardLevel(String safetyAwardLevel) {
        this.safetyAwardLevel = safetyAwardLevel;
    }
    
    public String getSafetyCertificateNumber() {
        return safetyCertificateNumber;
    }
    
    public void setSafetyCertificateNumber(String safetyCertificateNumber) {
        this.safetyCertificateNumber = safetyCertificateNumber;
    }
    
    public Integer getSafetyMilesLastMonth() {
        return safetyMilesLastMonth;
    }
    
    public void setSafetyMilesLastMonth(Integer safetyMilesLastMonth) {
        this.safetyMilesLastMonth = safetyMilesLastMonth;
    }
    
    public Integer getSafetyMilesNextMonth() {
        return safetyMilesNextMonth;
    }
    
    public void setSafetyMilesNextMonth(Integer safetyMilesNextMonth) {
        this.safetyMilesNextMonth = safetyMilesNextMonth;
    }
    
    public Integer getSafetyMilesThisMonth() {
        return safetyMilesThisMonth;
    }
    
    public void setSafetyMilesThisMonth(Integer safetyMilesThisMonth) {
        this.safetyMilesThisMonth = safetyMilesThisMonth;
    }
    
    public String getSpouseName() {
        return spouseName;
    }
    
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName;
    }
    
    public String getStarRank() {
        return starRank;
    }
    
    public void setStarRank(String starRank) {
        this.starRank = starRank;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Boolean getTankerQualified() {
        return tankerQualified;
    }
    
    public void setTankerQualified(Boolean tankerQualified) {
        this.tankerQualified = tankerQualified;
    }
    
    public String getTaxID() {
        return taxID;
    }
    
    public void setTaxID(String taxID) {
        this.taxID = taxID;
    }
    
    public Integer getTotalBond() {
        return totalBond;
    }
    
    public void setTotalBond(Integer totalBond) {
        this.totalBond = totalBond;
    }
    
    public Integer getTotalBondDraws() {
        return totalBondDraws;
    }
    
    public void setTotalBondDraws(Integer totalBondDraws) {
        this.totalBondDraws = totalBondDraws;
    }
    
    public Integer getTotalMiles() {
        return totalMiles;
    }
    
    public void setTotalMiles(Integer totalMiles) {
        this.totalMiles = totalMiles;
    }
    
    public Integer getSafetyMiles() {
        return safetyMiles;
    }
    
    public void setSafetyMiles(Integer safetyMiles) {
        this.safetyMiles = safetyMiles;
    }
    
    public Integer getTowCarWeight() {
        return towCarWeight;
    }
    
    public void setTowCarWeight(Integer towCarWeight) {
        this.towCarWeight = towCarWeight;
    }
    
    public Boolean getTowable() {
        return towable;
    }
    
    public void setTowable(Boolean towable) {
        this.towable = towable;
    }
    
    public String getTowableClass() {
        return towableClass;
    }
    
    public void setTowableClass(String towableClass) {
        this.towableClass = towableClass;
    }
    
    public Boolean getTowcar() {
        return towcar;
    }
    
    public void setTowcar(Boolean towcar) {
        this.towcar = towcar;
    }
    
    public Boolean getTractorQualified() {
        return tractorQualified;
    }
    
    public void setTractorQualified(Boolean tractorQualified) {
        this.tractorQualified = tractorQualified;
    }
    
    public String getTransportation() {
        return transportation;
    }
    
    public void setTransportation(String transportation) {
        this.transportation = transportation;
    }
    
    public Integer getTripCount() {
        return tripCount;
    }
    
    public void setTripCount(Integer tripCount) {
        this.tripCount = tripCount;
    }
    
    public Boolean getTruckingCompany() {
        return truckingCompany;
    }
    
    public void setTruckingCompany(Boolean truckingCompany) {
        this.truckingCompany = truckingCompany;
    }
    
    public Boolean getTwic() {
        return twic;
    }
    
    public void setTwic(Boolean twic) {
        this.twic = twic;
    }
    
    public Boolean getUndispatch() {
        return undispatch;
    }
    
    public void setUndispatch(Boolean undispatch) {
        this.undispatch = undispatch;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public Date getWeddingAnniversery() {
        return weddingAnniversery;
    }
    
    public void setWeddingAnniversery(Date weddingAnniversery) {
        this.weddingAnniversery = weddingAnniversery;
    }
    
    public Date getYesterdayCheckInDispatchDate() {
        return yesterdayCheckInDispatchDate;
    }
    
    public void setYesterdayCheckInDispatchDate(Date yesterdayCheckInDispatchDate) {
        this.yesterdayCheckInDispatchDate = yesterdayCheckInDispatchDate;
    }
    
    public Integer getYtd1099Amount() {
        return ytd1099Amount;
    }
    
    public void setYtd1099Amount(Integer ytd1099Amount) {
        this.ytd1099Amount = ytd1099Amount;
    }
    
    public String getCity() {
        return city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    public String getCountryCode() {
        return countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    
    public String getPostalCode() {
        return postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    public String getStateCode() {
        return stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    
    public String getAddress1() {
        return address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    
    public String getAddress2() {
        return address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    
    public String getPictureContentType() {
        return pictureContentType;
    }
    
    public void setPictureContentType(String pictureContentType) {
        this.pictureContentType = pictureContentType;
    }
    
    public String getPictureFile() {
        return pictureFile;
    }
    
    public void setPictureFile(String pictureFile) {
        this.pictureFile = pictureFile;
    }
    
    public BigInteger getCheckInDispatchFK() {
        return checkInDispatchFK;
    }
    
    public void setCheckInDispatchFK(BigInteger checkInDispatchFK) {
        this.checkInDispatchFK = checkInDispatchFK;
    }
    
    public BigInteger getCheckInUserFK() {
        return checkInUserFK;
    }
    
    public void setCheckInUserFK(BigInteger checkInUserFK) {
        this.checkInUserFK = checkInUserFK;
    }
    
    public String getDispatcherUserFK() {
        return dispatcherUserFK;
    }
    
    public void setDispatcherUserFK(String dispatcherUserFK) {
        this.dispatcherUserFK = dispatcherUserFK;
    }
    
    public BigInteger getDriverFiveStarFK() {
        return driverFiveStarFK;
    }
    
    public void setDriverFiveStarFK(BigInteger driverFiveStarFK) {
        this.driverFiveStarFK = driverFiveStarFK;
    }
    
    public BigInteger getLastDispatchedUserFK() {
        return lastDispatchedUserFK;
    }
    
    public void setLastDispatchedUserFK(BigInteger lastDispatchedUserFK) {
        this.lastDispatchedUserFK = lastDispatchedUserFK;
    }
    
    public BigInteger getOtherDriverFK() {
        return otherDriverFK;
    }
    
    public void setOtherDriverFK(BigInteger otherDriverFK) {
        this.otherDriverFK = otherDriverFK;
    }
    
    public BigInteger getPrimaryDriverFK() {
        return primaryDriverFK;
    }
    
    public void setPrimaryDriverFK(BigInteger primaryDriverFK) {
        this.primaryDriverFK = primaryDriverFK;
    }
    
    public BigInteger getRecruitingDriverFK() {
        return recruitingDriverFK;
    }
    
    public void setRecruitingDriverFK(BigInteger recruitingDriverFK) {
        this.recruitingDriverFK = recruitingDriverFK;
    }
    
    public BigInteger getYesterdayCheckInDispatchFK() {
        return yesterdayCheckInDispatchFK;
    }
    
    public void setYesterdayCheckInDispatchFK(BigInteger yesterdayCheckInDispatchFK) {
        this.yesterdayCheckInDispatchFK = yesterdayCheckInDispatchFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }
    
    public UserLogin getUserLogin() {
        return userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }


    public TlmDriver() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDriver))
            return false;
        TlmDriver equalCheck = (TlmDriver) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}