package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDriverTruck Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDriverTruck")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDriverTruck")
public class TlmDriverTruck implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "description")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String description;

    @Column(name = "dotInspectionExpirationDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date dotInspectionExpirationDate;

    @Column(name = "dotInspectionHold")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean dotInspectionHold;

    @Column(name = "dotInspectionHoldDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date dotInspectionHoldDate;

    @Column(name = "dotInspectionHoldReason")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dotInspectionHoldReason;

    @Column(name = "flatbed")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean flatbed;

    @Column(name = "gvwr")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer gvwr;

    @Column(name = "insuranceExpirationDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date insuranceExpirationDate;

    @Column(name = "leased")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean leased;

    @Column(name = "leftFrontTireSize")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String leftFrontTireSize;

    @Column(name = "leftRearInsideTireSize")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String leftRearInsideTireSize;

    @Column(name = "leftRearOutsideTireSize")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String leftRearOutsideTireSize;

    @Column(name = "licenseNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String licenseNumber;

    @Column(name = "licenseState")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String licenseState;

    @Column(name = "licenseWeight")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer licenseWeight;

    @Column(name = "make")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String make;

    @Column(name = "name")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String name;

    @Column(name = "nextMaintenanceReportDue")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String nextMaintenanceReportDue;

    @Column(name = "pintleHook")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean pintleHook;

    @Column(name = "registrationExpirationDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date registrationExpirationDate;

    @Column(name = "rightFrontTireSize")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String rightFrontTireSize;

    @Column(name = "rightRearInsideTireSize")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String rightRearInsideTireSize;

    @Column(name = "rightRearOutsideTireSize")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String rightRearOutsideTireSize;

    @Column(name = "scaleWeight")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer scaleWeight;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "truckType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String truckType;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "vin")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String vin;

    @Column(name = "year")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String year;

    @Column(name = "city")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String city;

    @Column(name = "countryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String countryCode;

    @Column(name = "postalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String postalCode;

    @Column(name = "stateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String stateCode;

    @Column(name = "address1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String address1;

    @Column(name = "address2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String address2;

    @Column(name = "ownerDriverFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger ownerDriverFK;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="driverId")
    private TlmDriver driver;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public Date getDotInspectionExpirationDate() {
        return dotInspectionExpirationDate;
    }
    
    public void setDotInspectionExpirationDate(Date dotInspectionExpirationDate) {
        this.dotInspectionExpirationDate = dotInspectionExpirationDate;
    }
    
    public Boolean getDotInspectionHold() {
        return dotInspectionHold;
    }
    
    public void setDotInspectionHold(Boolean dotInspectionHold) {
        this.dotInspectionHold = dotInspectionHold;
    }
    
    public Date getDotInspectionHoldDate() {
        return dotInspectionHoldDate;
    }
    
    public void setDotInspectionHoldDate(Date dotInspectionHoldDate) {
        this.dotInspectionHoldDate = dotInspectionHoldDate;
    }
    
    public String getDotInspectionHoldReason() {
        return dotInspectionHoldReason;
    }
    
    public void setDotInspectionHoldReason(String dotInspectionHoldReason) {
        this.dotInspectionHoldReason = dotInspectionHoldReason;
    }
    
    public Boolean getFlatbed() {
        return flatbed;
    }
    
    public void setFlatbed(Boolean flatbed) {
        this.flatbed = flatbed;
    }
    
    public Integer getGvwr() {
        return gvwr;
    }
    
    public void setGvwr(Integer gvwr) {
        this.gvwr = gvwr;
    }
    
    public Date getInsuranceExpirationDate() {
        return insuranceExpirationDate;
    }
    
    public void setInsuranceExpirationDate(Date insuranceExpirationDate) {
        this.insuranceExpirationDate = insuranceExpirationDate;
    }
    
    public Boolean getLeased() {
        return leased;
    }
    
    public void setLeased(Boolean leased) {
        this.leased = leased;
    }
    
    public String getLeftFrontTireSize() {
        return leftFrontTireSize;
    }
    
    public void setLeftFrontTireSize(String leftFrontTireSize) {
        this.leftFrontTireSize = leftFrontTireSize;
    }
    
    public String getLeftRearInsideTireSize() {
        return leftRearInsideTireSize;
    }
    
    public void setLeftRearInsideTireSize(String leftRearInsideTireSize) {
        this.leftRearInsideTireSize = leftRearInsideTireSize;
    }
    
    public String getLeftRearOutsideTireSize() {
        return leftRearOutsideTireSize;
    }
    
    public void setLeftRearOutsideTireSize(String leftRearOutsideTireSize) {
        this.leftRearOutsideTireSize = leftRearOutsideTireSize;
    }
    
    public String getLicenseNumber() {
        return licenseNumber;
    }
    
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber;
    }
    
    public String getLicenseState() {
        return licenseState;
    }
    
    public void setLicenseState(String licenseState) {
        this.licenseState = licenseState;
    }
    
    public Integer getLicenseWeight() {
        return licenseWeight;
    }
    
    public void setLicenseWeight(Integer licenseWeight) {
        this.licenseWeight = licenseWeight;
    }
    
    public String getMake() {
        return make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getNextMaintenanceReportDue() {
        return nextMaintenanceReportDue;
    }
    
    public void setNextMaintenanceReportDue(String nextMaintenanceReportDue) {
        this.nextMaintenanceReportDue = nextMaintenanceReportDue;
    }
    
    public Boolean getPintleHook() {
        return pintleHook;
    }
    
    public void setPintleHook(Boolean pintleHook) {
        this.pintleHook = pintleHook;
    }
    
    public Date getRegistrationExpirationDate() {
        return registrationExpirationDate;
    }
    
    public void setRegistrationExpirationDate(Date registrationExpirationDate) {
        this.registrationExpirationDate = registrationExpirationDate;
    }
    
    public String getRightFrontTireSize() {
        return rightFrontTireSize;
    }
    
    public void setRightFrontTireSize(String rightFrontTireSize) {
        this.rightFrontTireSize = rightFrontTireSize;
    }
    
    public String getRightRearInsideTireSize() {
        return rightRearInsideTireSize;
    }
    
    public void setRightRearInsideTireSize(String rightRearInsideTireSize) {
        this.rightRearInsideTireSize = rightRearInsideTireSize;
    }
    
    public String getRightRearOutsideTireSize() {
        return rightRearOutsideTireSize;
    }
    
    public void setRightRearOutsideTireSize(String rightRearOutsideTireSize) {
        this.rightRearOutsideTireSize = rightRearOutsideTireSize;
    }
    
    public Integer getScaleWeight() {
        return scaleWeight;
    }
    
    public void setScaleWeight(Integer scaleWeight) {
        this.scaleWeight = scaleWeight;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public String getTruckType() {
        return truckType;
    }
    
    public void setTruckType(String truckType) {
        this.truckType = truckType;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public String getVin() {
        return vin;
    }
    
    public void setVin(String vin) {
        this.vin = vin;
    }
    
    public String getYear() {
        return year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    
    public String getCity() {
        return city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    public String getCountryCode() {
        return countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    
    public String getPostalCode() {
        return postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    public String getStateCode() {
        return stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    
    public String getAddress1() {
        return address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    
    public String getAddress2() {
        return address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    
    public BigInteger getOwnerDriverFK() {
        return ownerDriverFK;
    }
    
    public void setOwnerDriverFK(BigInteger ownerDriverFK) {
        this.ownerDriverFK = ownerDriverFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDriver getDriver() {
        return driver;
    }
    
    public void setDriver(TlmDriver driver) {
        this.driver = driver;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmDriverTruck() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDriverTruck))
            return false;
        TlmDriverTruck equalCheck = (TlmDriverTruck) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}