package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDealerContact Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDealerContact")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDealerContact")
public class TlmDealerContact implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "breakdown")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean breakdown;

    @Column(name = "callback")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date callback;

    @Column(name = "checkIn")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean checkIn;

    @Column(name = "checkOut")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean checkOut;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "damage")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean damage;

    @Column(name = "delay")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean delay;

    @Column(name = "delivery")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean delivery;

    @Column(name = "email")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String email;

    @Column(name = "fax")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String fax;

    @Column(name = "lastCall")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastCall;

    @Column(name = "name")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String name;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "phone")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String phone;

    @Column(name = "reroute")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean reroute;

    @Column(name = "returned")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean returned;

    @Column(name = "contactRole")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String contactRole;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "undispatch")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean undispatch;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;
    
    @Column(name = "isLogin")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String isLogin;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="dealerId")
    private TlmDealer dealer;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;
    
    @ManyToOne
    @JoinColumn(name="userLoginId")
    private UserLogin userLogin;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Boolean getBreakdown() {
        return breakdown;
    }
    
    public void setBreakdown(Boolean breakdown) {
        this.breakdown = breakdown;
    }
    
    public Date getCallback() {
        return callback;
    }
    
    public void setCallback(Date callback) {
        this.callback = callback;
    }
    
    public Boolean getCheckIn() {
        return checkIn;
    }
    
    public void setCheckIn(Boolean checkIn) {
        this.checkIn = checkIn;
    }
    
    public Boolean getCheckOut() {
        return checkOut;
    }
    
    public void setCheckOut(Boolean checkOut) {
        this.checkOut = checkOut;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Boolean getDamage() {
        return damage;
    }
    
    public void setDamage(Boolean damage) {
        this.damage = damage;
    }
    
    public Boolean getDelay() {
        return delay;
    }
    
    public void setDelay(Boolean delay) {
        this.delay = delay;
    }
    
    public Boolean getDelivery() {
        return delivery;
    }
    
    public void setDelivery(Boolean delivery) {
        this.delivery = delivery;
    }
    
    public String getEmail() {
        return email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getFax() {
        return fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    public Date getLastCall() {
        return lastCall;
    }
    

     public String getIsLogin() {
        return isLogin;
    }
    
    public void setIsLogin(String isLogin) {
        this.isLogin = isLogin;
    }

    public void setLastCall(Date lastCall) {
        this.lastCall = lastCall;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public String getPhone() {
        return phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    public Boolean getReroute() {
        return reroute;
    }
    
    public void setReroute(Boolean reroute) {
        this.reroute = reroute;
    }
    
    public Boolean getReturned() {
        return returned;
    }
    
    public void setReturned(Boolean returned) {
        this.returned = returned;
    }
    
    public String getContactRole() {
        return contactRole;
    }
    
    public void setContactRole(String contactRole) {
        this.contactRole = contactRole;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Boolean getUndispatch() {
        return undispatch;
    }
    
    public void setUndispatch(Boolean undispatch) {
        this.undispatch = undispatch;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDealer getDealer() {
        return dealer;
    }
    
    public void setDealer(TlmDealer dealer) {
        this.dealer = dealer;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }
    
    public UserLogin getUserLogin() {
        return userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }


    public TlmDealerContact() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDealerContact))
            return false;
        TlmDealerContact equalCheck = (TlmDealerContact) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}