package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmDelayContact Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmDelayContact")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmDelayContact")
public class TlmDelayContact implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "breakdown")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean breakdown;

    @Column(name = "callback")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date callback;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "damaged")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean damaged;

    @Column(name = "delay")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean delay;

    @Column(name = "description")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String description;

    @Column(name = "email")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String email;

    @Column(name = "fax")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String fax;

    @Column(name = "lastCall")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastCall;

    @Column(name = "name")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String name;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "phone")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String phone;

    @Column(name = "representing")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String representing;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="customerId")
    private TlmCustomer customer;
    
    @ManyToOne
    @JoinColumn(name="delayedUnitId")
    private TlmDelayedUnit delayedUnit;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Boolean getBreakdown() {
        return breakdown;
    }
    
    public void setBreakdown(Boolean breakdown) {
        this.breakdown = breakdown;
    }
    
    public Date getCallback() {
        return callback;
    }
    
    public void setCallback(Date callback) {
        this.callback = callback;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Boolean getDamaged() {
        return damaged;
    }
    
    public void setDamaged(Boolean damaged) {
        this.damaged = damaged;
    }
    
    public Boolean getDelay() {
        return delay;
    }
    
    public void setDelay(Boolean delay) {
        this.delay = delay;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getEmail() {
        return email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getFax() {
        return fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    public Date getLastCall() {
        return lastCall;
    }
    
    public void setLastCall(Date lastCall) {
        this.lastCall = lastCall;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public String getPhone() {
        return phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    public String getRepresenting() {
        return representing;
    }
    
    public void setRepresenting(String representing) {
        this.representing = representing;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmCustomer getCustomer() {
        return customer;
    }
    
    public void setCustomer(TlmCustomer customer) {
        this.customer = customer;
    }
    
    public TlmDelayedUnit getDelayedUnit() {
        return delayedUnit;
    }
    
    public void setDelayedUnit(TlmDelayedUnit delayedUnit) {
        this.delayedUnit = delayedUnit;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmDelayContact() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmDelayContact))
            return false;
        TlmDelayContact equalCheck = (TlmDelayContact) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}