package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmEquipmentHistory Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmEquipmentHistory")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmEquipmentHistory")
public class TlmEquipmentHistory implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "checkInDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date checkInDate;

    @Column(name = "checkOutDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date checkOutDate;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "depositAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer depositAmount;

    @Column(name = "depositReference")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String depositReference;

    @Column(name = "refundAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer refundAmount;

    @Column(name = "refundReference")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String refundReference;

    @Column(name = "refundedDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date refundedDate;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "checkInUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger checkInUserFK;

    @Column(name = "checkOutUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger checkOutUserFK;

    @Column(name = "equipmentFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger equipmentFK;
     

     @ManyToOne
    @JoinColumn(name="equipmentId")
    private TlmEquipment equipment;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="driverId")
    private TlmDriver driver;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Date getCheckInDate() {
        return checkInDate;
    }
    
    public void setCheckInDate(Date checkInDate) {
        this.checkInDate = checkInDate;
    }
    
    public Date getCheckOutDate() {
        return checkOutDate;
    }
    
    public void setCheckOutDate(Date checkOutDate) {
        this.checkOutDate = checkOutDate;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Integer getDepositAmount() {
        return depositAmount;
    }
    
    public void setDepositAmount(Integer depositAmount) {
        this.depositAmount = depositAmount;
    }
    
    public String getDepositReference() {
        return depositReference;
    }
    
    public void setDepositReference(String depositReference) {
        this.depositReference = depositReference;
    }
    
    public Integer getRefundAmount() {
        return refundAmount;
    }
    
    public void setRefundAmount(Integer refundAmount) {
        this.refundAmount = refundAmount;
    }
    
    public String getRefundReference() {
        return refundReference;
    }
    
    public void setRefundReference(String refundReference) {
        this.refundReference = refundReference;
    }
    
    public Date getRefundedDate() {
        return refundedDate;
    }
    
    public void setRefundedDate(Date refundedDate) {
        this.refundedDate = refundedDate;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public BigInteger getCheckInUserFK() {
        return checkInUserFK;
    }
    
    public void setCheckInUserFK(BigInteger checkInUserFK) {
        this.checkInUserFK = checkInUserFK;
    }
    
    public BigInteger getCheckOutUserFK() {
        return checkOutUserFK;
    }
    
    public void setCheckOutUserFK(BigInteger checkOutUserFK) {
        this.checkOutUserFK = checkOutUserFK;
    }
    
    public BigInteger getEquipmentFK() {
        return equipmentFK;
    }
    
    public void setEquipmentFK(BigInteger equipmentFK) {
        this.equipmentFK = equipmentFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDriver getDriver() {
        return driver;
    }
    
    public void setDriver(TlmDriver driver) {
        this.driver = driver;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }
    
    public TlmEquipment getEquipment() { 
		return equipment;
	}

	public void setEquipment(TlmEquipment equipment) {
		this.equipment = equipment;
	}

	public TlmEquipmentHistory() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmEquipmentHistory))
            return false;
        TlmEquipmentHistory equalCheck = (TlmEquipmentHistory) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}