package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import javax.persistence.Id;
import java.util.Set;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmUnitDispatch Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmUnitDispatch")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmUnitDispatch")
public class TlmUnitDispatch implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "atFaultDamage")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean atFaultDamage;

    @Column(name = "bolNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer bolNumber;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "isDelayed")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String isDelayed;

    @Column(name = "deliveryAddressType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer deliveryAddressType;

    
     @Column(name = "deliveryCustomerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger deliveryCustomerFK;

    @Column(name = "deliveryDealerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger deliveryDealerFK;

    @Column(name = "deliveryFactoryFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger deliveryFactoryFK;

    @Column(name = "deliveryYardFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger deliveryYardFK;

    @Column(name = "dispatchDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date dispatchDate;

    @Column(name = "dispatchReplaceReason")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dispatchReplaceReason;

    @Column(name = "estimatedDeliveryDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date estimatedDeliveryDate;

    @Column(name = "estimatedEnRouteDays")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer estimatedEnRouteDays;

    @Column(name = "estimatedPickupDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date estimatedPickupDate;

    @Column(name = "lastLocationDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date lastLocationDate;

    @Column(name = "loadNumber")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer loadNumber;

    @Column(name = "multiUnit")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String multiUnit;

    @Column(name = "noRedispatch")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean noRedispatch;

    @Column(name = "partialTrip")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean partialTrip;

    @Column(name = "pickupAddressType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer pickupAddressType;

    @Column(name = "pickupCustomerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger pickupCustomerFK;

    @Column(name = "pickupDealerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger pickupDealerFK;

    @Column(name = "pickupFactoryFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger pickupFactoryFK;

    

    @Column(name = "pickupAfterDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date pickupAfterDate;

    @Column(name = "pickupBeforeDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date pickupBeforeDate;

    @Column(name = "isReturn")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Boolean isReturn;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "undispatchDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date undispatchDate;

    @Column(name = "undispatchReason")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String undispatchReason;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "checkinDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date checkinDate;
    
    @Column(name = "contractBonus")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer contractBonus;

    @Column(name = "contractFlatRate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer contractFlatRate;

    @Column(name = "contractMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer contractMiles;

    @Column(name = "contractRatePerMile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer contractRatePerMile;

    @Column(name = "contractRatingType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer contractRatingType;

    @Column(name = "contractTotalAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer contractTotalAmount;
    
    @Column(name = "delayDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date delayDate;

    @Column(name = "deliveryCity")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String deliveryCity;

    @Column(name = "deliveryCountryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String deliveryCountryCode;

    @Column(name = "deliveryAddrLatitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double deliveryAddrLatitude;

    @Column(name = "deliveryAddrLongitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double deliveryAddrLongitude;

    @Column(name = "deliveryPostalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String deliveryPostalCode;

    @Column(name = "deliveryStateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String deliveryStateCode;

    @Column(name = "deliveryAddress1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String deliveryAddress1;

    @Column(name = "deliveryAddress2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String deliveryAddress2;

    @Column(name = "locationCity")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String locationCity;

    @Column(name = "locationCountryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String locationCountryCode;

    @Column(name = "locationAddrLatitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double locationAddrLatitude;

    @Column(name = "locationAddrLongitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double locationAddrLongitude;

    @Column(name = "locationPostalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String locationPostalCode;

    @Column(name = "locationStateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String locationStateCode;

    @Column(name = "locationAddress1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String locationAddress1;

    @Column(name = "locationAddress2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String locationAddress2;
    
    @Column(name = "driverPaymentDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date driverPaymentDate;

    @Column(name = "paidBonus")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer paidBonus;

    @Column(name = "paidFlatRate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer paidFlatRate;

    @Column(name = "paidMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer paidMiles;

    @Column(name = "paidRatePerMile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer paidRatePerMile;

    @Column(name = "paidRatingType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer paidRatingType;

    @Column(name = "paidTotalAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer paidTotalAmount;

    @Column(name = "pickupCity")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pickupCity;

    @Column(name = "pickupCountryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pickupCountryCode;

    @Column(name = "pickupAddrLatitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double pickupAddrLatitude;

    @Column(name = "pickupAddrLongitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double pickupAddrLongitude;

    @Column(name = "pickupPostalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pickupPostalCode;

    @Column(name = "pickupStateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pickupStateCode;

    @Column(name = "pickupAddress1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pickupAddress1;

    @Column(name = "pickupAddress2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pickupAddress2;

    @Column(name = "delayCustomerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger delayCustomerFK;

    @Column(name = "delayDealerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger delayDealerFK;

    @Column(name = "delayFactoryFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger delayFactoryFK;

    @Column(name = "pickupYardFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String pickupYardFK;
    
    @Column(name = "delayYardFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String delayYardFK;


    @Column(name = "description")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String description;

    @Column(name = "delaytype")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String delaytype;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "loadNotes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String loadNotes;

    @Column(name = "enrouteNotes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String enrouteNotes;

    @Column(name = "dealerFinder")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String dealerFinder;

    @Column(name = "deliveredNotes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String deliveredNotes;

   
    @Column(name = "dispatchUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger dispatchUserFK;

    @Column(name = "driverTruckFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String driverTruckFK;

    @Column(name = "driverScheduleUpdateFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger driverScheduleUpdateFK;

    @Column(name = "undispatchUserFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger undispatchUserFK;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="yardId")
    private TlmYard yard;
    
    @ManyToOne
    @JoinColumn(name="unitTypeId")
    private TlmUnitType unitType;
    
    @ManyToOne
    @JoinColumn(name="driverId")
    private TlmDriver driver;

    @ManyToOne
    @JoinColumn(name="driverPaymentId")
    private TlmDriverPayment driverPayment;
    
    @ManyToOne
    @JoinColumn(name="checkinId")
    private TlmUnitCheckin checkin;
    
    @ManyToOne
    @JoinColumn(name="rerouteId")
    private TlmUnitReroute reroute;
    
    @ManyToOne
    @JoinColumn(name="delayedUnitId")
    private TlmDelayedUnit delayedUnit;
    
    @ManyToOne
    @JoinColumn(name="unitId")
    private TlmUnit unit;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;

     @ManyToOne
    @JoinColumn(name="customerId")
    private TlmCustomer customer;


@ManyToOne
    @JoinColumn(name="dealerId")
    private TlmDealer dealer;

    @ManyToOne
    @JoinColumn(name="factoryId")
    private TlmFactory factory;
    
    @ManyToOne
    @JoinColumn(name="unitRerouteId")
    private TlmUnitReroute unitReroute;

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Boolean getAtFaultDamage() {
        return atFaultDamage;
    }
    
    public void setAtFaultDamage(Boolean atFaultDamage) {
        this.atFaultDamage = atFaultDamage;
    }
    
    public Integer getBolNumber() {
        return bolNumber;
    }
    
    public void setBolNumber(Integer bolNumber) {
        this.bolNumber = bolNumber;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public String getIsDelayed() {
        return isDelayed;
    }

    public Date getCheckinDate() {
		return checkinDate;
	}

	public void setCheckinDate(Date checkinDate) {
		this.checkinDate = checkinDate;
	}

	public void setIsDelayed(String isDelayed) {
        this.isDelayed = isDelayed;
    }
    
    public Date getDelayDate() {
		return delayDate;
	}

	public void setDelayDate(Date delayDate) {
		this.delayDate = delayDate;
	}

     public BigInteger getPickupCustomerFK() {
        return pickupCustomerFK;
    }
    
    public void setPickupCustomerFK(BigInteger pickupCustomerFK) {
        this.pickupCustomerFK = pickupCustomerFK;
    }
    
    public BigInteger getPickupDealerFK() {
        return pickupDealerFK;
    }
    
    public void setPickupDealerFK(BigInteger pickupDealerFK) {
        this.pickupDealerFK = pickupDealerFK;
    }
    
    public BigInteger getPickupFactoryFK() {
        return pickupFactoryFK;
    }
    
    public void setPickupFactoryFK(BigInteger pickupFactoryFK) {
        this.pickupFactoryFK = pickupFactoryFK;
    }
    
    
    

	public Integer getDeliveryAddressType() {
        return deliveryAddressType;
    }
    
    public void setDeliveryAddressType(Integer deliveryAddressType) {
        this.deliveryAddressType = deliveryAddressType;
    }
    
    public Date getDispatchDate() {
        return dispatchDate;
    }
    
    public void setDispatchDate(Date dispatchDate) {
        this.dispatchDate = dispatchDate;
    }
    
    public String getDispatchReplaceReason() {
        return dispatchReplaceReason;
    }
    
    public void setDispatchReplaceReason(String dispatchReplaceReason) {
        this.dispatchReplaceReason = dispatchReplaceReason;
    }
    

     public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


     public String getDealerFinder() {
        return dealerFinder;
    }
    
    public void setDealerFinder(String dealerFinder) {
        this.dealerFinder = dealerFinder;
    }

public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getLoadNotes() {
        return loadNotes;
    }
    
    public void setLoadNotes(String loadNotes) {
        this.loadNotes = loadNotes;
    }
    public String getEnrouteNotes() {
        return enrouteNotes;
    }
    
    public void setEnrouteNotes(String enrouteNotes) {
        this.enrouteNotes = enrouteNotes;
    }
    public String getDeliveredNotes() {
        return deliveredNotes;
    }
    
    public void setDeliveredNotes(String deliveredNotes) {
        this.deliveredNotes = deliveredNotes;
    }

public String getDelaytype() {
        return delaytype;
    }
    
    public void setDelaytype(String delaytype) {
        this.delaytype = delaytype;
    }
public BigInteger getDeliveryCustomerFK() {
        return deliveryCustomerFK;
    }
    
    public void setDeliveryCustomerFK(BigInteger deliveryCustomerFK) {
        this.deliveryCustomerFK = deliveryCustomerFK;
    }
    
    public BigInteger getDeliveryDealerFK() {
        return deliveryDealerFK;
    }
    
    public void setDeliveryDealerFK(BigInteger deliveryDealerFK) {
        this.deliveryDealerFK = deliveryDealerFK;
    }
    
    public BigInteger getDeliveryFactoryFK() {
        return deliveryFactoryFK;
    }
    
    public void setDeliveryFactoryFK(BigInteger deliveryFactoryFK) {
        this.deliveryFactoryFK = deliveryFactoryFK;
    }
    
    public BigInteger getDeliveryYardFK() {
        return deliveryYardFK;
    }
    
    public void setDeliveryYardFK(BigInteger deliveryYardFK) {
        this.deliveryYardFK = deliveryYardFK;
    }
    


    public Date getEstimatedDeliveryDate() {
        return estimatedDeliveryDate;
    }
    
    public void setEstimatedDeliveryDate(Date estimatedDeliveryDate) {
        this.estimatedDeliveryDate = estimatedDeliveryDate;
    }
    
    public Integer getEstimatedEnRouteDays() {
        return estimatedEnRouteDays;
    }
    
    public void setEstimatedEnRouteDays(Integer estimatedEnRouteDays) {
        this.estimatedEnRouteDays = estimatedEnRouteDays;
    }
    
    public Date getEstimatedPickupDate() {
        return estimatedPickupDate;
    }
    
    public void setEstimatedPickupDate(Date estimatedPickupDate) {
        this.estimatedPickupDate = estimatedPickupDate;
    }
    
    public Date getLastLocationDate() {
        return lastLocationDate;
    }
    
    public void setLastLocationDate(Date lastLocationDate) {
        this.lastLocationDate = lastLocationDate;
    }
    
    public Integer getLoadNumber() {
        return loadNumber;
    }
    
    public void setLoadNumber(Integer loadNumber) {
        this.loadNumber = loadNumber;
    }
    
    public String getMultiUnit() {
        return multiUnit;
    }
    
    public void setMultiUnit(String multiUnit) {
        this.multiUnit = multiUnit;
    }
    
    public Boolean getNoRedispatch() {
        return noRedispatch;
    }
    
    public void setNoRedispatch(Boolean noRedispatch) {
        this.noRedispatch = noRedispatch;
    }
    
    public Boolean getPartialTrip() {
        return partialTrip;
    }
    
    public void setPartialTrip(Boolean partialTrip) {
        this.partialTrip = partialTrip;
    }
    
    public Integer getPickupAddressType() {
        return pickupAddressType;
    }
    
    public void setPickupAddressType(Integer pickupAddressType) {
        this.pickupAddressType = pickupAddressType;
    }
    
    public Date getPickupAfterDate() {
        return pickupAfterDate;
    }
    
    public void setPickupAfterDate(Date pickupAfterDate) {
        this.pickupAfterDate = pickupAfterDate;
    }
    
    public Date getPickupBeforeDate() {
        return pickupBeforeDate;
    }
    
    public void setPickupBeforeDate(Date pickupBeforeDate) {
        this.pickupBeforeDate = pickupBeforeDate;
    }
    
    public Boolean getIsReturn() {
        return isReturn;
    }
    
    public void setIsReturn(Boolean isReturn) {
        this.isReturn = isReturn;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Date getUndispatchDate() {
        return undispatchDate;
    }
    
    public void setUndispatchDate(Date undispatchDate) {
        this.undispatchDate = undispatchDate;
    }
    
    public String getUndispatchReason() {
        return undispatchReason;
    }
    
    public void setUndispatchReason(String undispatchReason) {
        this.undispatchReason = undispatchReason;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public Integer getContractBonus() {
        return contractBonus;
    }
    
    public void setContractBonus(Integer contractBonus) {
        this.contractBonus = contractBonus;
    }
    
    public Integer getContractFlatRate() {
        return contractFlatRate;
    }
    
    public void setContractFlatRate(Integer contractFlatRate) {
        this.contractFlatRate = contractFlatRate;
    }
    
    public Integer getContractMiles() {
        return contractMiles;
    }
    
    public void setContractMiles(Integer contractMiles) {
        this.contractMiles = contractMiles;
    }
    
    public Integer getContractRatePerMile() {
        return contractRatePerMile;
    }
    
    public void setContractRatePerMile(Integer contractRatePerMile) {
        this.contractRatePerMile = contractRatePerMile;
    }
    
    public Integer getContractRatingType() {
        return contractRatingType;
    }
    
    public void setContractRatingType(Integer contractRatingType) {
        this.contractRatingType = contractRatingType;
    }
    
    public Integer getContractTotalAmount() {
        return contractTotalAmount;
    }
    
    public void setContractTotalAmount(Integer contractTotalAmount) {
        this.contractTotalAmount = contractTotalAmount;
    }
    
    public String getDeliveryCity() {
        return deliveryCity;
    }
    
    public void setDeliveryCity(String deliveryCity) {
        this.deliveryCity = deliveryCity;
    }
    
    public String getDeliveryCountryCode() {
        return deliveryCountryCode;
    }
    
    public void setDeliveryCountryCode(String deliveryCountryCode) {
        this.deliveryCountryCode = deliveryCountryCode;
    }
    
    public Double getDeliveryAddrLatitude() {
        return deliveryAddrLatitude;
    }
    
    public void setDeliveryAddrLatitude(Double deliveryAddrLatitude) {
        this.deliveryAddrLatitude = deliveryAddrLatitude;
    }
    
    public Double getDeliveryAddrLongitude() {
        return deliveryAddrLongitude;
    }
    
    public void setDeliveryAddrLongitude(Double deliveryAddrLongitude) {
        this.deliveryAddrLongitude = deliveryAddrLongitude;
    }
    
    public String getDeliveryPostalCode() {
        return deliveryPostalCode;
    }
    
    public void setDeliveryPostalCode(String deliveryPostalCode) {
        this.deliveryPostalCode = deliveryPostalCode;
    }
    
 public BigInteger getDelayCustomerFK() {
        return delayCustomerFK;
    }
    
    public void setDelayCustomerFK(BigInteger delayCustomerFK) {
        this.delayCustomerFK = delayCustomerFK;
    }
    
    public BigInteger getDelayDealerFK() {
        return delayDealerFK;
    }
    
    public void setDelayDealerFK(BigInteger delayDealerFK) {
        this.delayDealerFK = delayDealerFK;
    }
    
    public BigInteger getDelayFactoryFK() {
        return delayFactoryFK;
    }
    
    public void setDelayFactoryFK(BigInteger delayFactoryFK) {
        this.delayFactoryFK = delayFactoryFK;
    }

    public String getDeliveryStateCode() {
        return deliveryStateCode;
    }
    
    public void setDeliveryStateCode(String deliveryStateCode) {
        this.deliveryStateCode = deliveryStateCode;
    }
    
    public String getDeliveryAddress1() {
        return deliveryAddress1;
    }
    
    public void setDeliveryAddress1(String deliveryAddress1) {
        this.deliveryAddress1 = deliveryAddress1;
    }
    
    public String getDeliveryAddress2() {
        return deliveryAddress2;
    }
    
    public void setDeliveryAddress2(String deliveryAddress2) {
        this.deliveryAddress2 = deliveryAddress2;
    }
    
    public String getLocationCity() {
        return locationCity;
    }
    
    public void setLocationCity(String locationCity) {
        this.locationCity = locationCity;
    }
    
    public String getLocationCountryCode() {
        return locationCountryCode;
    }
    
    public void setLocationCountryCode(String locationCountryCode) {
        this.locationCountryCode = locationCountryCode;
    }
    
    public Double getLocationAddrLatitude() {
        return locationAddrLatitude;
    }
    
    public void setLocationAddrLatitude(Double locationAddrLatitude) {
        this.locationAddrLatitude = locationAddrLatitude;
    }
    
    public Double getLocationAddrLongitude() {
        return locationAddrLongitude;
    }
    
    public void setLocationAddrLongitude(Double locationAddrLongitude) {
        this.locationAddrLongitude = locationAddrLongitude;
    }
    
    public String getLocationPostalCode() {
        return locationPostalCode;
    }
    
    public void setLocationPostalCode(String locationPostalCode) {
        this.locationPostalCode = locationPostalCode;
    }
    
    public String getLocationStateCode() {
        return locationStateCode;
    }
    
    public void setLocationStateCode(String locationStateCode) {
        this.locationStateCode = locationStateCode;
    }
    
    public String getLocationAddress1() {
        return locationAddress1;
    }
    
    public void setLocationAddress1(String locationAddress1) {
        this.locationAddress1 = locationAddress1;
    }
    
    public String getLocationAddress2() {
        return locationAddress2;
    }
    
    public void setLocationAddress2(String locationAddress2) {
        this.locationAddress2 = locationAddress2;
    }
    
    public Date getDriverPaymentDate() {
		return driverPaymentDate;
	}

	public void setDriverPaymentDate(Date driverPaymentDate) {
		this.driverPaymentDate = driverPaymentDate;
	}

	public Integer getPaidBonus() { 
        return paidBonus;
    }
    
    public void setPaidBonus(Integer paidBonus) {
        this.paidBonus = paidBonus;
    }
    
    public Integer getPaidFlatRate() {
        return paidFlatRate;
    }
    
    public void setPaidFlatRate(Integer paidFlatRate) {
        this.paidFlatRate = paidFlatRate;
    }
    
    public Integer getPaidMiles() {
        return paidMiles;
    }
    
    public void setPaidMiles(Integer paidMiles) {
        this.paidMiles = paidMiles;
    }
    
    public Integer getPaidRatePerMile() {
        return paidRatePerMile;
    }
    
    public void setPaidRatePerMile(Integer paidRatePerMile) {
        this.paidRatePerMile = paidRatePerMile;
    }
    
    public Integer getPaidRatingType() {
        return paidRatingType;
    }
    
    public void setPaidRatingType(Integer paidRatingType) {
        this.paidRatingType = paidRatingType;
    }
    
    public Integer getPaidTotalAmount() {
        return paidTotalAmount;
    }
    
    public void setPaidTotalAmount(Integer paidTotalAmount) {
        this.paidTotalAmount = paidTotalAmount;
    }
       
    public String getPickupYardFK() {
		return pickupYardFK;
	}

	public void setPickupYardFK(String pickupYardFK) {
		this.pickupYardFK = pickupYardFK;
	}

	public String getDelayYardFK() {
		return delayYardFK;
	}

	public void setDelayYardFK(String delayYardFK) {
		this.delayYardFK = delayYardFK;
	}

	public String getPickupCity() {
        return pickupCity;
    }
    
    public void setPickupCity(String pickupCity) {
        this.pickupCity = pickupCity;
    }
    
    public String getPickupCountryCode() {
        return pickupCountryCode;
    }
    
    public void setPickupCountryCode(String pickupCountryCode) {
        this.pickupCountryCode = pickupCountryCode;
    }
    
    public Double getPickupAddrLatitude() {
        return pickupAddrLatitude;
    }
    
    public void setPickupAddrLatitude(Double pickupAddrLatitude) {
        this.pickupAddrLatitude = pickupAddrLatitude;
    }
    
    public Double getPickupAddrLongitude() {
        return pickupAddrLongitude;
    }
    
    public void setPickupAddrLongitude(Double pickupAddrLongitude) {
        this.pickupAddrLongitude = pickupAddrLongitude;
    }
    
    public String getPickupPostalCode() {
        return pickupPostalCode;
    }
    
    public void setPickupPostalCode(String pickupPostalCode) {
        this.pickupPostalCode = pickupPostalCode;
    }
    
    public String getPickupStateCode() {
        return pickupStateCode;
    }
    
    public void setPickupStateCode(String pickupStateCode) {
        this.pickupStateCode = pickupStateCode;
    }
    
    public String getPickupAddress1() {
        return pickupAddress1;
    }
    
    public void setPickupAddress1(String pickupAddress1) {
        this.pickupAddress1 = pickupAddress1;
    }
    
    public String getPickupAddress2() {
        return pickupAddress2;
    }
    
    public void setPickupAddress2(String pickupAddress2) {
        this.pickupAddress2 = pickupAddress2;
    }
    
    public BigInteger getDispatchUserFK() {
        return dispatchUserFK;
    }
    
    public void setDispatchUserFK(BigInteger dispatchUserFK) {
        this.dispatchUserFK = dispatchUserFK;
    }
    
    public String getDriverTruckFK() {
        return driverTruckFK;
    }
    
    public void setDriverTruckFK(String driverTruckFK) {
        this.driverTruckFK = driverTruckFK;
    }
    
    public BigInteger getDriverScheduleUpdateFK() {
        return driverScheduleUpdateFK;
    }
    
    public void setDriverScheduleUpdateFK(BigInteger driverScheduleUpdateFK) {
        this.driverScheduleUpdateFK = driverScheduleUpdateFK;
    }
    
    public BigInteger getUndispatchUserFK() {
        return undispatchUserFK;
    }
    
    public void setUndispatchUserFK(BigInteger undispatchUserFK) {
        this.undispatchUserFK = undispatchUserFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmYard getYard() {
        return yard;
    }
    
    public void setYard(TlmYard yard) {
        this.yard = yard;
    }
    
     public TlmCustomer getCustomer() {
        return customer;
    }
    
    public void setCustomer(TlmCustomer customer) {
        this.customer = customer;
    }

    public TlmDealer getDealer() {
        return dealer;
    }
    
    public void setDealer(TlmDealer dealer) {
        this.dealer = dealer;
    }
    
public TlmFactory getFactory() {
        return factory;
    }
    
    public void setFactory(TlmFactory factory) {
        this.factory = factory;
    }
    
    public TlmUnitType getUnitType() {
        return unitType;
    }
    
    public void setUnitType(TlmUnitType unitType) {
        this.unitType = unitType;
    }
    
    public TlmDriver getDriver() {
        return driver;
    }
    
    public void setDriver(TlmDriver driver) {
        this.driver = driver;
    }

    public TlmDriverPayment getDriverPayment() {
        return driverPayment;
    }
    
    public void setDriverPayment(TlmDriverPayment driverPayment) {
        this.driverPayment = driverPayment;
    }
    
    public TlmUnitCheckin getCheckin() {
        return checkin;
    }
    
    public void setCheckin(TlmUnitCheckin checkin) {
        this.checkin = checkin;
    }
    public TlmUnitReroute getReroute() {
        return reroute;
    }
    
    public void setReroute(TlmUnitReroute reroute) {
        this.reroute = reroute;
    }
    
    public TlmDelayedUnit getDelayedUnit() {
        return delayedUnit;
    }
    
    public void setDelayedUnit(TlmDelayedUnit delayedUnit) {
        this.delayedUnit = delayedUnit;
    }
    
    public TlmUnit getUnit() {
        return unit;
    }
    
    public void setUnit(TlmUnit unit) {
        this.unit = unit;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }

    public TlmUnitReroute getUnitReroute() {
		return unitReroute;
	}

	public void setUnitReroute(TlmUnitReroute unitReroute) {
		this.unitReroute = unitReroute;
	}

	public TlmUnitDispatch() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmUnitDispatch))
            return false;
        TlmUnitDispatch equalCheck = (TlmUnitDispatch) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}