package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmUnitDocument Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmUnitDocument")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmUnitDocument")
public class TlmUnitDocument implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "description")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String description;

    @Column(name = "documentKey")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String documentKey;

    @Column(name = "documentType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String documentType;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "documentContentType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String documentContentType;

    @Column(name = "documentFile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String documentFile;

    @Column(name = "invoiceFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger invoiceFK;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="delayedUnitId")
    private TlmDelayedUnit delayedUnit;
    
    @ManyToOne
    @JoinColumn(name="dispatchId")
    private TlmUnitDispatch dispatch;
    
    @ManyToOne
    @JoinColumn(name="unitId")
    private TlmUnit unit;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getDocumentKey() {
        return documentKey;
    }
    
    public void setDocumentKey(String documentKey) {
        this.documentKey = documentKey;
    }
    
    public String getDocumentType() {
        return documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public String getDocumentContentType() {
        return documentContentType;
    }
    
    public void setDocumentContentType(String documentContentType) {
        this.documentContentType = documentContentType;
    }
    
    public String getDocumentFile() {
        return documentFile;
    }
    
    public void setDocumentFile(String documentFile) {
        this.documentFile = documentFile;
    }
    
    public BigInteger getInvoiceFK() {
        return invoiceFK;
    }
    
    public void setInvoiceFK(BigInteger invoiceFK) {
        this.invoiceFK = invoiceFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmDelayedUnit getDelayedUnit() {
        return delayedUnit;
    }
    
    public void setDelayedUnit(TlmDelayedUnit delayedUnit) {
        this.delayedUnit = delayedUnit;
    }
    
    public TlmUnitDispatch getDispatch() {
        return dispatch;
    }
    
    public void setDispatch(TlmUnitDispatch dispatch) {
        this.dispatch = dispatch;
    }
    
    public TlmUnit getUnit() {
        return unit;
    }
    
    public void setUnit(TlmUnit unit) {
        this.unit = unit;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmUnitDocument() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmUnitDocument))
            return false;
        TlmUnitDocument equalCheck = (TlmUnitDocument) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}