package com.eLogoSoft.cwrv.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * TlmUnitReroute Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "TlmUnitReroute")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "ELogoSoftRest/com/eLogoSoft/cwrv/domain", name = "TlmUnitReroute")
public class TlmUnitReroute implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "authorizedBy")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String authorizedBy;

    @Column(name = "changeType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String changeType;

    @Column(name = "addDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date addDate;

    @Column(name = "newAddressType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newAddressType;

    @Column(name = "notes")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String notes;

    @Column(name = "oldAddressType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldAddressType;

    @Column(name = "rerouteDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date rerouteDate;

    @Column(name = "status")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String status;

    @Column(name = "unitLocation")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String unitLocation;

    @Column(name = "updateDate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date updateDate;

    @Column(name = "version")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer version;

    @Column(name = "newCity")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String newCity;

    @Column(name = "newCountryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String newCountryCode;

    @Column(name = "newAddrLatitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double newAddrLatitude;

    @Column(name = "newAddrLongitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double newAddrLongitude;

    @Column(name = "newPostalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String newPostalCode;

    @Column(name = "newStateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String newStateCode;

    @Column(name = "newAddress1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String newAddress1;

    @Column(name = "newAddress2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String newAddress2;

    @Column(name = "newDriverBonus")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newDriverBonus;

    @Column(name = "newDriverFlatRate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newDriverFlatRate;

    @Column(name = "newDriverMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newDriverMiles;

    @Column(name = "newDriverRatePerMile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newDriverRatePerMile;

    @Column(name = "newDriverRatingType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newDriverRatingType;

    @Column(name = "newDriverTotalAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newDriverTotalAmount;

    @Column(name = "newInvoiceBonus")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newInvoiceBonus;

    @Column(name = "newInvoiceFlatRate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newInvoiceFlatRate;

    @Column(name = "newInvoiceMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newInvoiceMiles;

    @Column(name = "newInvoiceRatePerMile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newInvoiceRatePerMile;

    @Column(name = "newInvoiceRatingType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newInvoiceRatingType;

    @Column(name = "newInvoiceTotalAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer newInvoiceTotalAmount;

    @Column(name = "oldCity")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String oldCity;

    @Column(name = "oldCountryCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String oldCountryCode;

    @Column(name = "oldAddrLatitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double oldAddrLatitude;

    @Column(name = "oldAddrLongitude")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Double oldAddrLongitude;

    @Column(name = "oldPostalCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String oldPostalCode;

    @Column(name = "oldStateCode")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String oldStateCode;

    @Column(name = "oldAddress1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String oldAddress1;

    @Column(name = "oldAddress2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String oldAddress2;

    @Column(name = "oldDriverBonus")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldDriverBonus;

    @Column(name = "oldDriverFlatRate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldDriverFlatRate;

    @Column(name = "oldDriverMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldDriverMiles;

    @Column(name = "oldDriverRatePerMile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldDriverRatePerMile;

    @Column(name = "oldDriverRatingType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldDriverRatingType;

    @Column(name = "oldDriverTotalAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldDriverTotalAmount;

    @Column(name = "oldInvoiceBonus")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldInvoiceBonus;

    @Column(name = "oldInvoiceFlatRate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldInvoiceFlatRate;

    @Column(name = "oldInvoiceMiles")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldInvoiceMiles;

    @Column(name = "oldInvoiceRatePerMile")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldInvoiceRatePerMile;

    @Column(name = "oldInvoiceRatingType")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldInvoiceRatingType;

    @Column(name = "oldInvoiceTotalAmount")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer oldInvoiceTotalAmount;

    @Column(name = "newAddressCustomerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger newAddressCustomerFK;

    @Column(name = "newAddressDealerFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String newAddressDealerFK;

    @Column(name = "newAddressFactoryFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger newAddressFactoryFK;

    @Column(name = "newAddressYardFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger newAddressYardFK;

    @Column(name = "unitStatusFK")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private BigInteger unitStatusFK;
    
    
    @ManyToOne
    @JoinColumn(name="addUserId")
    private UserLogin addUser;
    
    @ManyToOne
    @JoinColumn(name="dispatchId")
    private TlmUnitDispatch dispatch;
    
    @ManyToOne
    @JoinColumn(name="unitId")
    private TlmUnit unit;
    
    @ManyToOne
    @JoinColumn(name="updateUserId")
    private UserLogin updateUser;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getAuthorizedBy() {
        return authorizedBy;
    }
    
    public void setAuthorizedBy(String authorizedBy) {
        this.authorizedBy = authorizedBy;
    }
    
    public String getChangeType() {
        return changeType;
    }
    
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }
    
    public Date getAddDate() {
        return addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    public Integer getNewAddressType() {
        return newAddressType;
    }
    
    public void setNewAddressType(Integer newAddressType) {
        this.newAddressType = newAddressType;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public Integer getOldAddressType() {
        return oldAddressType;
    }
    
    public void setOldAddressType(Integer oldAddressType) {
        this.oldAddressType = oldAddressType;
    }
    
    public Date getRerouteDate() {
        return rerouteDate;
    }
    
    public void setRerouteDate(Date rerouteDate) {
        this.rerouteDate = rerouteDate;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public String getUnitLocation() {
        return unitLocation;
    }
    
    public void setUnitLocation(String unitLocation) {
        this.unitLocation = unitLocation;
    }
    
    public Date getUpdateDate() {
        return updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public Integer getVersion() {
        return version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public String getNewCity() {
        return newCity;
    }
    
    public void setNewCity(String newCity) {
        this.newCity = newCity;
    }
    
    public String getNewCountryCode() {
        return newCountryCode;
    }
    
    public void setNewCountryCode(String newCountryCode) {
        this.newCountryCode = newCountryCode;
    }
    
    public Double getNewAddrLatitude() {
        return newAddrLatitude;
    }
    
    public void setNewAddrLatitude(Double newAddrLatitude) {
        this.newAddrLatitude = newAddrLatitude;
    }
    
    public Double getNewAddrLongitude() {
        return newAddrLongitude;
    }
    
    public void setNewAddrLongitude(Double newAddrLongitude) {
        this.newAddrLongitude = newAddrLongitude;
    }
    
    public String getNewPostalCode() {
        return newPostalCode;
    }
    
    public void setNewPostalCode(String newPostalCode) {
        this.newPostalCode = newPostalCode;
    }
    
    public String getNewStateCode() {
        return newStateCode;
    }
    
    public void setNewStateCode(String newStateCode) {
        this.newStateCode = newStateCode;
    }
    
    public String getNewAddress1() {
        return newAddress1;
    }
    
    public void setNewAddress1(String newAddress1) {
        this.newAddress1 = newAddress1;
    }
    
    public String getNewAddress2() {
        return newAddress2;
    }
    
    public void setNewAddress2(String newAddress2) {
        this.newAddress2 = newAddress2;
    }
    
    public Integer getNewDriverBonus() {
        return newDriverBonus;
    }
    
    public void setNewDriverBonus(Integer newDriverBonus) {
        this.newDriverBonus = newDriverBonus;
    }
    
    public Integer getNewDriverFlatRate() {
        return newDriverFlatRate;
    }
    
    public void setNewDriverFlatRate(Integer newDriverFlatRate) {
        this.newDriverFlatRate = newDriverFlatRate;
    }
    
    public Integer getNewDriverMiles() {
        return newDriverMiles;
    }
    
    public void setNewDriverMiles(Integer newDriverMiles) {
        this.newDriverMiles = newDriverMiles;
    }
    
    public Integer getNewDriverRatePerMile() {
        return newDriverRatePerMile;
    }
    
    public void setNewDriverRatePerMile(Integer newDriverRatePerMile) {
        this.newDriverRatePerMile = newDriverRatePerMile;
    }
    
    public Integer getNewDriverRatingType() {
        return newDriverRatingType;
    }
    
    public void setNewDriverRatingType(Integer newDriverRatingType) {
        this.newDriverRatingType = newDriverRatingType;
    }
    
    public Integer getNewDriverTotalAmount() {
        return newDriverTotalAmount;
    }
    
    public void setNewDriverTotalAmount(Integer newDriverTotalAmount) {
        this.newDriverTotalAmount = newDriverTotalAmount;
    }
    
    public Integer getNewInvoiceBonus() {
        return newInvoiceBonus;
    }
    
    public void setNewInvoiceBonus(Integer newInvoiceBonus) {
        this.newInvoiceBonus = newInvoiceBonus;
    }
    
    public Integer getNewInvoiceFlatRate() {
        return newInvoiceFlatRate;
    }
    
    public void setNewInvoiceFlatRate(Integer newInvoiceFlatRate) {
        this.newInvoiceFlatRate = newInvoiceFlatRate;
    }
    
    public Integer getNewInvoiceMiles() {
        return newInvoiceMiles;
    }
    
    public void setNewInvoiceMiles(Integer newInvoiceMiles) {
        this.newInvoiceMiles = newInvoiceMiles;
    }
    
    public Integer getNewInvoiceRatePerMile() {
        return newInvoiceRatePerMile;
    }
    
    public void setNewInvoiceRatePerMile(Integer newInvoiceRatePerMile) {
        this.newInvoiceRatePerMile = newInvoiceRatePerMile;
    }
    
    public Integer getNewInvoiceRatingType() {
        return newInvoiceRatingType;
    }
    
    public void setNewInvoiceRatingType(Integer newInvoiceRatingType) {
        this.newInvoiceRatingType = newInvoiceRatingType;
    }
    
    public Integer getNewInvoiceTotalAmount() {
        return newInvoiceTotalAmount;
    }
    
    public void setNewInvoiceTotalAmount(Integer newInvoiceTotalAmount) {
        this.newInvoiceTotalAmount = newInvoiceTotalAmount;
    }
    
    public String getOldCity() {
        return oldCity;
    }
    
    public void setOldCity(String oldCity) {
        this.oldCity = oldCity;
    }
    
    public String getOldCountryCode() {
        return oldCountryCode;
    }
    
    public void setOldCountryCode(String oldCountryCode) {
        this.oldCountryCode = oldCountryCode;
    }
    
    public Double getOldAddrLatitude() {
        return oldAddrLatitude;
    }
    
    public void setOldAddrLatitude(Double oldAddrLatitude) {
        this.oldAddrLatitude = oldAddrLatitude;
    }
    
    public Double getOldAddrLongitude() {
        return oldAddrLongitude;
    }
    
    public void setOldAddrLongitude(Double oldAddrLongitude) {
        this.oldAddrLongitude = oldAddrLongitude;
    }
    
    public String getOldPostalCode() {
        return oldPostalCode;
    }
    
    public void setOldPostalCode(String oldPostalCode) {
        this.oldPostalCode = oldPostalCode;
    }
    
    public String getOldStateCode() {
        return oldStateCode;
    }
    
    public void setOldStateCode(String oldStateCode) {
        this.oldStateCode = oldStateCode;
    }
    
    public String getOldAddress1() {
        return oldAddress1;
    }
    
    public void setOldAddress1(String oldAddress1) {
        this.oldAddress1 = oldAddress1;
    }
    
    public String getOldAddress2() {
        return oldAddress2;
    }
    
    public void setOldAddress2(String oldAddress2) {
        this.oldAddress2 = oldAddress2;
    }
    
    public Integer getOldDriverBonus() {
        return oldDriverBonus;
    }
    
    public void setOldDriverBonus(Integer oldDriverBonus) {
        this.oldDriverBonus = oldDriverBonus;
    }
    
    public Integer getOldDriverFlatRate() {
        return oldDriverFlatRate;
    }
    
    public void setOldDriverFlatRate(Integer oldDriverFlatRate) {
        this.oldDriverFlatRate = oldDriverFlatRate;
    }
    
    public Integer getOldDriverMiles() {
        return oldDriverMiles;
    }
    
    public void setOldDriverMiles(Integer oldDriverMiles) {
        this.oldDriverMiles = oldDriverMiles;
    }
    
    public Integer getOldDriverRatePerMile() {
        return oldDriverRatePerMile;
    }
    
    public void setOldDriverRatePerMile(Integer oldDriverRatePerMile) {
        this.oldDriverRatePerMile = oldDriverRatePerMile;
    }
    
    public Integer getOldDriverRatingType() {
        return oldDriverRatingType;
    }
    
    public void setOldDriverRatingType(Integer oldDriverRatingType) {
        this.oldDriverRatingType = oldDriverRatingType;
    }
    
    public Integer getOldDriverTotalAmount() {
        return oldDriverTotalAmount;
    }
    
    public void setOldDriverTotalAmount(Integer oldDriverTotalAmount) {
        this.oldDriverTotalAmount = oldDriverTotalAmount;
    }
    
    public Integer getOldInvoiceBonus() {
        return oldInvoiceBonus;
    }
    
    public void setOldInvoiceBonus(Integer oldInvoiceBonus) {
        this.oldInvoiceBonus = oldInvoiceBonus;
    }
    
    public Integer getOldInvoiceFlatRate() {
        return oldInvoiceFlatRate;
    }
    
    public void setOldInvoiceFlatRate(Integer oldInvoiceFlatRate) {
        this.oldInvoiceFlatRate = oldInvoiceFlatRate;
    }
    
    public Integer getOldInvoiceMiles() {
        return oldInvoiceMiles;
    }
    
    public void setOldInvoiceMiles(Integer oldInvoiceMiles) {
        this.oldInvoiceMiles = oldInvoiceMiles;
    }
    
    public Integer getOldInvoiceRatePerMile() {
        return oldInvoiceRatePerMile;
    }
    
    public void setOldInvoiceRatePerMile(Integer oldInvoiceRatePerMile) {
        this.oldInvoiceRatePerMile = oldInvoiceRatePerMile;
    }
    
    public Integer getOldInvoiceRatingType() {
        return oldInvoiceRatingType;
    }
    
    public void setOldInvoiceRatingType(Integer oldInvoiceRatingType) {
        this.oldInvoiceRatingType = oldInvoiceRatingType;
    }
    
    public Integer getOldInvoiceTotalAmount() {
        return oldInvoiceTotalAmount;
    }
    
    public void setOldInvoiceTotalAmount(Integer oldInvoiceTotalAmount) {
        this.oldInvoiceTotalAmount = oldInvoiceTotalAmount;
    }
    
    public BigInteger getNewAddressCustomerFK() {
        return newAddressCustomerFK;
    }
    
    public void setNewAddressCustomerFK(BigInteger newAddressCustomerFK) {
        this.newAddressCustomerFK = newAddressCustomerFK;
    }
    
    public String getNewAddressDealerFK() {
        return newAddressDealerFK;
    }
    
    public void setNewAddressDealerFK(String newAddressDealerFK) {
        this.newAddressDealerFK = newAddressDealerFK;
    }
    
    public BigInteger getNewAddressFactoryFK() {
        return newAddressFactoryFK;
    }
    
    public void setNewAddressFactoryFK(BigInteger newAddressFactoryFK) {
        this.newAddressFactoryFK = newAddressFactoryFK;
    }
    
    public BigInteger getNewAddressYardFK() {
        return newAddressYardFK;
    }
    
    public void setNewAddressYardFK(BigInteger newAddressYardFK) {
        this.newAddressYardFK = newAddressYardFK;
    }
    
    public BigInteger getUnitStatusFK() {
        return unitStatusFK;
    }
    
    public void setUnitStatusFK(BigInteger unitStatusFK) {
        this.unitStatusFK = unitStatusFK;
    }
    
    public UserLogin getAddUser() {
        return addUser;
    }
    
    public void setAddUser(UserLogin addUser) {
        this.addUser = addUser;
    }
    
    public TlmUnitDispatch getDispatch() {
        return dispatch;
    }
    
    public void setDispatch(TlmUnitDispatch dispatch) {
        this.dispatch = dispatch;
    }
    
    public TlmUnit getUnit() {
        return unit;
    }
    
    public void setUnit(TlmUnit unit) {
        this.unit = unit;
    }
    
    public UserLogin getUpdateUser() {
        return updateUser;
    }
    
    public void setUpdateUser(UserLogin updateUser) {
        this.updateUser = updateUser;
    }


    public TlmUnitReroute() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof TlmUnitReroute))
            return false;
        TlmUnitReroute equalCheck = (TlmUnitReroute) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}